"""Fixtures for tests."""

import pytest

from fpl.model.managers_models import ManagerTeamData
from fpl.model.players_models import PlayerDetail


@pytest.fixture
def fixture_player_match_fixture_data():
    """Fixture for player fixture data."""
    return {
        "id": 1,
        "code": 100,
        "team_h": 1,
        "team_h_score": 2,
        "team_a": 2,
        "team_a_score": 1,
        "event": 1,
        "finished": True,
        "minutes": 90,
        "provisional_start_time": False,
        "kickoff_time": "2023-10-01T12:30:00Z",
        "event_name": "Gameweek 1",
        "is_home": True,
        "difficulty": 3,
    }


@pytest.fixture
def fixture_history_data():
    """Fixture for current season data"""
    return {
        "element": 1,
        "fixture": 1,
        "opponent_team": 2,
        "total_points": 10,
        "was_home": True,
        "kickoff_time": "2023-10-01T12:30:00Z",
        "team_h_score": 2,
        "team_a_score": 1,
        "round": 1,
        "minutes": 90,
        "goals_scored": 1,
        "assists": 1,
        "clean_sheets": 1,
        "goals_conceded": 0,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "saves": 0,
        "bonus": 3,
        "bps": 30,
        "influence": "100.0",
        "creativity": "50.0",
        "threat": "75.0",
        "ict_index": "225.0",
        "starts": 1,
        "expected_goals": "0.5",
        "expected_assists": "0.3",
        "expected_goal_involvements": "0.8",
        "expected_goals_conceded": "0.2",
        "value": 100,
        "transfers_balance": 10,
        "selected": 1000,
        "transfers_in": 50,
        "transfers_out": 40,
    }


@pytest.fixture
def fixture_history_past_data():
    """Fixture for past season data data."""
    return {
        "season_name": "2022/23",
        "element_code": 1,
        "start_cost": 100,
        "end_cost": 110,
        "total_points": 200,
        "minutes": 3000,
        "goals_scored": 20,
        "assists": 10,
        "clean_sheets": 15,
        "goals_conceded": 25,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 1,
        "yellow_cards": 3,
        "red_cards": 0,
        "saves": 0,
        "bonus": 30,
        "bps": 300,
        "influence": "500.0",
        "creativity": "200.0",
        "threat": "300.0",
        "ict_index": "1000.0",
        "starts": 35,
        "expected_goals": "10.0",
        "expected_assists": "5.0",
        "expected_goal_involvements": "15.0",
        "expected_goals_conceded": "20.0",
    }


@pytest.fixture
def fixture_player_detail_data():
    """Fixture for player detail data."""
    return {
        "chance_of_playing_next_round": 0,
        "chance_of_playing_this_round": 0,
        "code": 438098,
        "cost_change_event": 0,
        "cost_change_event_fall": 0,
        "cost_change_start": -1,
        "cost_change_start_fall": 1,
        "dreamteam_count": 0,
        "element_type": 3,
        "ep_next": "0.0",
        "ep_this": "0.0",
        "event_points": 0,
        "first_name": "Fábio",
        "form": "0.0",
        "id": 1,
        "in_dreamteam": False,
        "news": "Has joined Portuguese side FC Porto on loan for the 2024/25 season",
        "news_added": "2024-08-29T11:06:25.241953Z",
        "now_cost": 54,
        "photo": "438098.jpg",
        "points_per_game": "0.0",
        "second_name": "Ferreira Vieira",
        "selected_by_percent": "0.0",
        "special": False,
        "squad_number": None,
        "status": "u",
        "team": 1,
        "team_code": 3,
        "total_points": 0,
        "transfers_in": 439,
        "transfers_in_event": 0,
        "transfers_out": 2172,
        "transfers_out_event": 664,
        "value_form": "0.0",
        "value_season": "0.0",
        "web_name": "Fábio Vieira",
        "region": None,
        "minutes": 0,
        "goals_scored": 0,
        "assists": 0,
        "clean_sheets": 0,
        "goals_conceded": 0,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "saves": 0,
        "bonus": 0,
        "bps": 0,
        "influence": "0.0",
        "creativity": "0.0",
        "threat": "0.0",
        "ict_index": "0.0",
        "starts": 0,
        "expected_goals": "0.00",
        "expected_assists": "0.00",
        "expected_goal_involvements": "0.00",
        "expected_goals_conceded": "0.00",
        "influence_rank": 628,
        "influence_rank_type": 284,
        "creativity_rank": 627,
        "creativity_rank_type": 286,
        "threat_rank": 617,
        "threat_rank_type": 280,
        "ict_index_rank": 631,
        "ict_index_rank_type": 287,
        "corners_and_indirect_freekicks_order": None,
        "corners_and_indirect_freekicks_text": "",
        "direct_freekicks_order": None,
        "direct_freekicks_text": "",
        "penalties_order": None,
        "penalties_text": "",
        "expected_goals_per_90": 0,
        "saves_per_90": 0,
        "expected_assists_per_90": 0,
        "expected_goal_involvements_per_90": 0,
        "expected_goals_conceded_per_90": 0,
        "goals_conceded_per_90": 0,
        "now_cost_rank": 167,
        "now_cost_rank_type": 104,
        "form_rank": 627,
        "form_rank_type": 286,
        "points_per_game_rank": 627,
        "points_per_game_rank_type": 286,
        "selected_rank": 593,
        "selected_rank_type": 260,
        "starts_per_90": 0,
        "clean_sheets_per_90": 0,
    }


@pytest.fixture
def fixture_player_data(
    fixture_player_match_fixture_data,
    fixture_history_data,
    fixture_history_past_data,
):
    return {
        "fixtures": [fixture_player_match_fixture_data],
        "history": [fixture_history_data],
        "history_past": [fixture_history_past_data],
    }


@pytest.fixture
def fixture_players_bootstrap_data(fixture_player_detail_data):
    """Fixture for bootstrap data."""
    return {"elements": [fixture_player_detail_data]}


@pytest.fixture
def fixture_league_data():
    """Fixture for league data."""
    return {
        "new_entries": {"has_next": False, "page": 1, "results": []},
        "last_updated_data": "2024-09-28T19:49:21Z",
        "league": {
            "id": 1,
            "name": "Arsenal",
            "created": "2024-07-17T11:51:46.252125Z",
            "closed": False,
            "max_entries": None,
            "league_type": "s",
            "scoring": "c",
            "admin_entry": None,
            "start_event": 1,
            "code_privacy": "p",
            "has_cup": True,
            "cup_league": None,
            "rank": None,
        },
        "standings": {
            "has_next": True,
            "page": 1,
            "results": [
                {
                    "id": 46599801,
                    "event_total": 96,
                    "player_name": "Ajdin Selimovic",
                    "rank": 1,
                    "last_rank": 193,
                    "rank_sort": 1,
                    "total": 513,
                    "entry": 5932784,
                    "entry_name": "Ronaldinhovic",
                },
                {
                    "id": 9178578,
                    "event_total": 53,
                    "player_name": "tunjay ozer",
                    "rank": 2,
                    "last_rank": 1,
                    "rank_sort": 2,
                    "total": 508,
                    "entry": 1432938,
                    "entry_name": "yeah buddy",
                },
                {
                    "id": 49695302,
                    "event_total": 72,
                    "player_name": "Khalil Nasreddin",
                    "rank": 3,
                    "last_rank": 46,
                    "rank_sort": 3,
                    "total": 498,
                    "entry": 6139538,
                    "entry_name": "النصر لحمااس",
                },
                {
                    "id": 14428798,
                    "event_total": 48,
                    "player_name": "Youssef Ben Turkia",
                    "rank": 4,
                    "last_rank": 2,
                    "rank_sort": 4,
                    "total": 495,
                    "entry": 2197936,
                    "entry_name": "Selim1925",
                },
                {
                    "id": 3273903,
                    "event_total": 73,
                    "player_name": "دردقي بشيش",
                    "rank": 5,
                    "last_rank": 97,
                    "rank_sort": 5,
                    "total": 494,
                    "entry": 524830,
                    "entry_name": "فانتازي دبنقا",
                },
                {
                    "id": 51752719,
                    "event_total": 58,
                    "player_name": "Al-Hamza Al-Absi",
                    "rank": 6,
                    "last_rank": 18,
                    "rank_sort": 6,
                    "total": 492,
                    "entry": 6309120,
                    "entry_name": "Maestro",
                },
                {
                    "id": 7385956,
                    "event_total": 72,
                    "player_name": "Elwazzan Elwazzan",
                    "rank": 7,
                    "last_rank": 133,
                    "rank_sort": 7,
                    "total": 491,
                    "entry": 1160256,
                    "entry_name": "الوزان",
                },
                {
                    "id": 45590678,
                    "event_total": 85,
                    "player_name": "Sileman Harki",
                    "rank": 8,
                    "last_rank": 834,
                    "rank_sort": 8,
                    "total": 491,
                    "entry": 5863704,
                    "entry_name": "silemankurdi",
                },
                {
                    "id": 21829325,
                    "event_total": 82,
                    "player_name": "Barham Jabara",
                    "rank": 9,
                    "last_rank": 658,
                    "rank_sort": 9,
                    "total": 490,
                    "entry": 3212728,
                    "entry_name": "barham1234",
                },
                {
                    "id": 63953654,
                    "event_total": 70,
                    "player_name": "James Jeffery",
                    "rank": 10,
                    "last_rank": 150,
                    "rank_sort": 10,
                    "total": 488,
                    "entry": 7586446,
                    "entry_name": "Jeffery10 United",
                },
                {
                    "id": 57264230,
                    "event_total": 60,
                    "player_name": "Ibrahim Alamamy",
                    "rank": 11,
                    "last_rank": 23,
                    "rank_sort": 11,
                    "total": 488,
                    "entry": 6875353,
                    "entry_name": "B E M O",
                },
                {
                    "id": 21084873,
                    "event_total": 89,
                    "player_name": "عمر أبوحكيم",
                    "rank": 12,
                    "last_rank": 2485,
                    "rank_sort": 12,
                    "total": 486,
                    "entry": 3113192,
                    "entry_name": "صہٰاحہٰبٰٰ الُِڪوُرة",
                },
                {
                    "id": 61679379,
                    "event_total": 43,
                    "player_name": "Ahmed Ditto",
                    "rank": 13,
                    "last_rank": 5,
                    "rank_sort": 13,
                    "total": 485,
                    "entry": 7350500,
                    "entry_name": "Ditto.FC",
                },
                {
                    "id": 1207293,
                    "event_total": 59,
                    "player_name": "24 JAM",
                    "rank": 14,
                    "last_rank": 26,
                    "rank_sort": 14,
                    "total": 485,
                    "entry": 197639,
                    "entry_name": "Caterpillar",
                },
                {
                    "id": 68754206,
                    "event_total": 46,
                    "player_name": "ahmed khaled",
                    "rank": 15,
                    "last_rank": 8,
                    "rank_sort": 15,
                    "total": 484,
                    "entry": 8076406,
                    "entry_name": "ابوكتف�",
                },
                {
                    "id": 10549293,
                    "event_total": 77,
                    "player_name": "Jan Popelínský",
                    "rank": 16,
                    "last_rank": 432,
                    "rank_sort": 16,
                    "total": 484,
                    "entry": 1636078,
                    "entry_name": "SexyMan",
                },
                {
                    "id": 4228484,
                    "event_total": 64,
                    "player_name": "Nikola Vasić",
                    "rank": 17,
                    "last_rank": 150,
                    "rank_sort": 17,
                    "total": 482,
                    "entry": 673844,
                    "entry_name": "Argoulides",
                },
                {
                    "id": 1873910,
                    "event_total": 85,
                    "player_name": "Salim Suleiman",
                    "rank": 17,
                    "last_rank": 2393,
                    "rank_sort": 18,
                    "total": 482,
                    "entry": 302997,
                    "entry_name": "Gwena FC",
                },
                {
                    "id": 24211267,
                    "event_total": 82,
                    "player_name": "Tiago T",
                    "rank": 19,
                    "last_rank": 1701,
                    "rank_sort": 19,
                    "total": 482,
                    "entry": 3526742,
                    "entry_name": "Tielemans Square1989",
                },
                {
                    "id": 69505316,
                    "event_total": 57,
                    "player_name": "muhammad naim",
                    "rank": 20,
                    "last_rank": 58,
                    "rank_sort": 20,
                    "total": 482,
                    "entry": 8152480,
                    "entry_name": "Arsenal07",
                },
                {
                    "id": 14771159,
                    "event_total": 55,
                    "player_name": "Yonael Afework",
                    "rank": 21,
                    "last_rank": 45,
                    "rank_sort": 21,
                    "total": 482,
                    "entry": 2246314,
                    "entry_name": "yonaellll",
                },
                {
                    "id": 16507214,
                    "event_total": 64,
                    "player_name": "Erik Pettersson",
                    "rank": 22,
                    "last_rank": 176,
                    "rank_sort": 22,
                    "total": 481,
                    "entry": 2489812,
                    "entry_name": "FC Bendtnerlona",
                },
                {
                    "id": 10793269,
                    "event_total": 47,
                    "player_name": "Kye Calvy",
                    "rank": 23,
                    "last_rank": 22,
                    "rank_sort": 23,
                    "total": 480,
                    "entry": 1670842,
                    "entry_name": "CUCU CUCURELLA",
                },
                {
                    "id": 8888216,
                    "event_total": 61,
                    "player_name": "Hashem ZR",
                    "rank": 24,
                    "last_rank": 139,
                    "rank_sort": 24,
                    "total": 480,
                    "entry": 1388490,
                    "entry_name": "HashemZr",
                },
                {
                    "id": 26830106,
                    "event_total": 49,
                    "player_name": "Hridesh Wagle",
                    "rank": 25,
                    "last_rank": 7,
                    "rank_sort": 25,
                    "total": 480,
                    "entry": 3860569,
                    "entry_name": "GoodBoy Gunner �",
                },
                {
                    "id": 48513986,
                    "event_total": 64,
                    "player_name": "Sayed Ali",
                    "rank": 26,
                    "last_rank": 243,
                    "rank_sort": 26,
                    "total": 479,
                    "entry": 6053249,
                    "entry_name": "قلب البابا",
                },
                {
                    "id": 46933185,
                    "event_total": 50,
                    "player_name": "rebin ali",
                    "rank": 27,
                    "last_rank": 32,
                    "rank_sort": 27,
                    "total": 479,
                    "entry": 5953948,
                    "entry_name": "shery fantasy",
                },
                {
                    "id": 37522503,
                    "event_total": 56,
                    "player_name": "nyamwanga boy",
                    "rank": 27,
                    "last_rank": 75,
                    "rank_sort": 28,
                    "total": 479,
                    "entry": 5135935,
                    "entry_name": "TANZANIA  1",
                },
                {
                    "id": 8574633,
                    "event_total": 74,
                    "player_name": "Benny Angeles",
                    "rank": 27,
                    "last_rank": 932,
                    "rank_sort": 29,
                    "total": 479,
                    "entry": 1340247,
                    "entry_name": "115 Charges FC",
                },
                {
                    "id": 11871468,
                    "event_total": 77,
                    "player_name": "Andy Neale",
                    "rank": 30,
                    "last_rank": 819,
                    "rank_sort": 30,
                    "total": 479,
                    "entry": 1826126,
                    "entry_name": "Arteta's Vision",
                },
                {
                    "id": 10559941,
                    "event_total": 61,
                    "player_name": "Paul Abbott",
                    "rank": 31,
                    "last_rank": 176,
                    "rank_sort": 31,
                    "total": 478,
                    "entry": 1637688,
                    "entry_name": "Roaring Wild Shins",
                },
                {
                    "id": 46755814,
                    "event_total": 68,
                    "player_name": "upi 0opah",
                    "rank": 32,
                    "last_rank": 494,
                    "rank_sort": 32,
                    "total": 478,
                    "entry": 5942818,
                    "entry_name": "elweskheen",
                },
                {
                    "id": 25672458,
                    "event_total": 75,
                    "player_name": "Terry Khawaja",
                    "rank": 32,
                    "last_rank": 1199,
                    "rank_sort": 33,
                    "total": 478,
                    "entry": 3710566,
                    "entry_name": "Bad boys for life",
                },
                {
                    "id": 62880879,
                    "event_total": 54,
                    "player_name": "Stergios Andreoglou",
                    "rank": 34,
                    "last_rank": 65,
                    "rank_sort": 34,
                    "total": 478,
                    "entry": 7475598,
                    "entry_name": "Gunners 21",
                },
                {
                    "id": 45460069,
                    "event_total": 77,
                    "player_name": "Ahmed Ali",
                    "rank": 34,
                    "last_rank": 1507,
                    "rank_sort": 35,
                    "total": 478,
                    "entry": 5855477,
                    "entry_name": "2الزنجي المعجزه",
                },
                {
                    "id": 29454720,
                    "event_total": 70,
                    "player_name": "Ahmed Madkour",
                    "rank": 36,
                    "last_rank": 740,
                    "rank_sort": 36,
                    "total": 477,
                    "entry": 4131524,
                    "entry_name": "HOBI",
                },
                {
                    "id": 32714067,
                    "event_total": 88,
                    "player_name": "Adam Brismo",
                    "rank": 36,
                    "last_rank": 5639,
                    "rank_sort": 37,
                    "total": 477,
                    "entry": 4548098,
                    "entry_name": "HeMan",
                },
                {
                    "id": 53769495,
                    "event_total": 61,
                    "player_name": "Paul Ovens",
                    "rank": 38,
                    "last_rank": 224,
                    "rank_sort": 38,
                    "total": 477,
                    "entry": 6502948,
                    "entry_name": "haven’tgotimeforthis",
                },
                {
                    "id": 1975973,
                    "event_total": 73,
                    "player_name": "Karan Vir Negi",
                    "rank": 38,
                    "last_rank": 1066,
                    "rank_sort": 39,
                    "total": 477,
                    "entry": 319175,
                    "entry_name": "Old Havertz Kai Hard",
                },
                {
                    "id": 56125796,
                    "event_total": 82,
                    "player_name": "Augustine Ebubeogu",
                    "rank": 38,
                    "last_rank": 3016,
                    "rank_sort": 40,
                    "total": 477,
                    "entry": 6753586,
                    "entry_name": "Stinelee",
                },
                {
                    "id": 17870856,
                    "event_total": 85,
                    "player_name": "David Jones",
                    "rank": 38,
                    "last_rank": 4145,
                    "rank_sort": 41,
                    "total": 477,
                    "entry": 2679834,
                    "entry_name": "Djibouti FC",
                },
                {
                    "id": 53553071,
                    "event_total": 60,
                    "player_name": "Sam Callcut",
                    "rank": 42,
                    "last_rank": 193,
                    "rank_sort": 42,
                    "total": 477,
                    "entry": 6479949,
                    "entry_name": "Saka White Rice",
                },
                {
                    "id": 27814024,
                    "event_total": 66,
                    "player_name": "Abdulio .",
                    "rank": 42,
                    "last_rank": 432,
                    "rank_sort": 43,
                    "total": 477,
                    "entry": 3945686,
                    "entry_name": "King Kai",
                },
                {
                    "id": 14154386,
                    "event_total": 57,
                    "player_name": "James Morris",
                    "rank": 44,
                    "last_rank": 133,
                    "rank_sort": 44,
                    "total": 476,
                    "entry": 2156730,
                    "entry_name": "Jim's Janglies",
                },
                {
                    "id": 4658691,
                    "event_total": 66,
                    "player_name": "Yehia 🇪🇬🇵🇸",
                    "rank": 44,
                    "last_rank": 480,
                    "rank_sort": 45,
                    "total": 476,
                    "entry": 741337,
                    "entry_name": "Yehia",
                },
                {
                    "id": 30139986,
                    "event_total": 57,
                    "player_name": "Louie Heron",
                    "rank": 46,
                    "last_rank": 133,
                    "rank_sort": 46,
                    "total": 476,
                    "entry": 4216381,
                    "entry_name": "Mosgiel Metapods",
                },
                {
                    "id": 51066576,
                    "event_total": 92,
                    "player_name": "yassin zakaria",
                    "rank": 46,
                    "last_rank": 9876,
                    "rank_sort": 47,
                    "total": 476,
                    "entry": 6261743,
                    "entry_name": "yassinzakaria",
                },
                {
                    "id": 61203460,
                    "event_total": 83,
                    "player_name": "Yahia Ltf",
                    "rank": 48,
                    "last_rank": 4145,
                    "rank_sort": 48,
                    "total": 475,
                    "entry": 7299374,
                    "entry_name": "Quelle BUT",
                },
                {
                    "id": 3139680,
                    "event_total": 54,
                    "player_name": "Mohamed Ali",
                    "rank": 49,
                    "last_rank": 100,
                    "rank_sort": 49,
                    "total": 475,
                    "entry": 503352,
                    "entry_name": "Three (A)",
                },
                {
                    "id": 12261491,
                    "event_total": 56,
                    "player_name": "Alex Scofield",
                    "rank": 49,
                    "last_rank": 130,
                    "rank_sort": 50,
                    "total": 475,
                    "entry": 1883694,
                    "entry_name": "Scözil XI",
                },
            ],
        },
    }


@pytest.fixture
def picks_data_no_chip():
    return {
        "active_chip": None,
        "automatic_subs": [],
        "entry_history": {
            "event": 1,
            "points": 54,
            "total_points": 54,
            "rank": 5141847,
            "rank_sort": 5141847,
            "overall_rank": 5141845,
            "percentile_rank": 60,
            "bank": 5,
            "value": 1000,
            "event_transfers": 0,
            "event_transfers_cost": 0,
            "points_on_bench": 5,
        },
        "picks": [
            {
                "element": 201,
                "position": 1,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 422,
                "position": 2,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 3,
                "position": 3,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 333,
                "position": 4,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 366,
                "position": 5,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 317,
                "position": 6,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 54,
                "position": 7,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 17,
                "position": 8,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": True,
            },
            {
                "element": 351,
                "position": 9,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 401,
                "position": 10,
                "multiplier": 2,
                "is_captain": True,
                "is_vice_captain": False,
            },
            {
                "element": 82,
                "position": 11,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 536,
                "position": 12,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 19,
                "position": 13,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 255,
                "position": 14,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 275,
                "position": 15,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
        ],
    }


@pytest.fixture
def fixture_picks_data_wildcard():
    return {
        "active_chip": "wildcard",
        "automatic_subs": [],
        "entry_history": {
            "event": 1,
            "points": 54,
            "total_points": 54,
            "rank": 5141847,
            "rank_sort": 5141847,
            "overall_rank": 5141845,
            "percentile_rank": 60,
            "bank": 5,
            "value": 1000,
            "event_transfers": 0,
            "event_transfers_cost": 0,
            "points_on_bench": 5,
        },
        "picks": [
            {
                "element": 201,
                "position": 1,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 422,
                "position": 2,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 3,
                "position": 3,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 333,
                "position": 4,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 366,
                "position": 5,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 317,
                "position": 6,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 54,
                "position": 7,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 17,
                "position": 8,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": True,
            },
            {
                "element": 351,
                "position": 9,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 401,
                "position": 10,
                "multiplier": 2,
                "is_captain": True,
                "is_vice_captain": False,
            },
            {
                "element": 82,
                "position": 11,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 536,
                "position": 12,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 19,
                "position": 13,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 255,
                "position": 14,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 275,
                "position": 15,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
        ],
    }


@pytest.fixture
def fixture_team_forest():
    return {
        "code": 17,
        "draw": 0,
        "form": None,
        "id": 16,
        "loss": 0,
        "name": "Nott'm Forest",
        "played": 0,
        "points": 0,
        "position": 0,
        "short_name": "NFO",
        "strength": 3,
        "team_division": None,
        "unavailable": False,
        "win": 0,
        "strength_overall_home": 1090,
        "strength_overall_away": 1100,
        "strength_attack_home": 1085,
        "strength_attack_away": 1115,
        "strength_defence_home": 1090,
        "strength_defence_away": 1090,
        "pulse_id": 15,
    }


@pytest.fixture
def fixture_team_newcastle():
    return {
        "code": 4,
        "draw": 0,
        "form": None,
        "id": 15,
        "loss": 0,
        "name": "Newcastle",
        "played": 0,
        "points": 0,
        "position": 0,
        "short_name": "NEW",
        "strength": 4,
        "team_division": None,
        "unavailable": False,
        "win": 0,
        "strength_overall_home": 1130,
        "strength_overall_away": 1285,
        "strength_attack_home": 1100,
        "strength_attack_away": 1185,
        "strength_defence_home": 1160,
        "strength_defence_away": 1380,
        "pulse_id": 23,
    }


@pytest.fixture
def fixture_team_bootstrap_data(fixture_team_forest, fixture_team_newcastle):
    return {
        "teams": [
            fixture_team_forest,
            fixture_team_newcastle,
        ]
    }


@pytest.fixture
def fixture_player_picks_list(fixture_picks_data_wildcard, picks_data_no_chip):
    """Fixture for test_get_player_analysis."""
    return [
        ManagerTeamData(**picks_data_no_chip),
        ManagerTeamData(**fixture_picks_data_wildcard),
    ]


@pytest.fixture
def fixture_player_detail_for_average_team():
    """Player data for average team so that the get player detail does not produce a KeyError."""
    return {
        201: PlayerDetail(
            chance_of_playing_next_round=None,
            chance_of_playing_this_round=None,
            code=172649,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=-1,
            cost_change_start_fall=1,
            dreamteam_count=2,
            element_type=1,
            ep_next="3.8",
            ep_this="2.8",
            event_points=1,
            first_name="Dean",
            form="3.8",
            id=201,
            in_dreamteam=False,
            news="",
            news_added=None,
            now_cost=44,
            photo="172649.jpg",
            points_per_game="3.5",
            second_name="Henderson",
            selected_by_percent="10.3",
            special=False,
            squad_number=None,
            status="a",
            team=7,
            team_code=31,
            total_points=53,
            transfers_in=635298,
            transfers_in_event=9750,
            transfers_out=1231703,
            transfers_out_event=4142,
            value_form="0.9",
            value_season="12.0",
            web_name="Henderson",
            region=241,
            minutes=1350,
            goals_scored=0,
            assists=0,
            clean_sheets=3,
            goals_conceded=20,
            own_goals=0,
            penalties_saved=1,
            penalties_missed=0,
            yellow_cards=1,
            red_cards=0,
            saves=46,
            bonus=4,
            bps=179,
            influence="384.4",
            creativity="0.0",
            threat="4.0",
            ict_index="38.8",
            starts=15,
            expected_goals="0.01",
            expected_assists="0.00",
            expected_goal_involvements="0.01",
            expected_goals_conceded="21.26",
            influence_rank=17,
            influence_rank_type=5,
            creativity_rank=551,
            creativity_rank_type=57,
            threat_rank=373,
            threat_rank_type=1,
            ict_index_rank=170,
            ict_index_rank_type=5,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.0,
            saves_per_90=3.07,
            expected_assists_per_90=0.0,
            expected_goal_involvements_per_90=0.0,
            expected_goals_conceded_per_90=1.42,
            goals_conceded_per_90=1.33,
            now_cost_rank=484,
            now_cost_rank_type=20,
            form_rank=46,
            form_rank_type=4,
            points_per_game_rank=74,
            points_per_game_rank_type=10,
            selected_rank=36,
            selected_rank_type=7,
            starts_per_90=1.0,
            clean_sheets_per_90=0.2,
            position="Goalkeeper",
        ),
        422: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=159506,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=4,
            cost_change_start_fall=-4,
            dreamteam_count=3,
            element_type=2,
            ep_next="2.2",
            ep_this="2.2",
            event_points=1,
            first_name="Ola",
            form="2.2",
            id=422,
            in_dreamteam=False,
            news="",
            news_added="2024-11-21T08:30:09.347848Z",
            now_cost=49,
            photo="159506.jpg",
            points_per_game="3.9",
            second_name="Aina",
            selected_by_percent="14.4",
            special=False,
            squad_number=None,
            status="a",
            team=16,
            team_code=17,
            total_points=58,
            transfers_in=2019269,
            transfers_in_event=27414,
            transfers_out=657936,
            transfers_out_event=13217,
            value_form="0.4",
            value_season="11.8",
            web_name="Aina",
            region=157,
            minutes=1283,
            goals_scored=1,
            assists=0,
            clean_sheets=5,
            goals_conceded=17,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=2,
            red_cards=0,
            saves=0,
            bonus=10,
            bps=229,
            influence="265.8",
            creativity="124.0",
            threat="31.0",
            ict_index="42.1",
            starts=15,
            expected_goals="0.11",
            expected_assists="1.13",
            expected_goal_involvements="1.24",
            expected_goals_conceded="16.10",
            influence_rank=81,
            influence_rank_type=29,
            creativity_rank=147,
            creativity_rank_type=31,
            threat_rank=270,
            threat_rank_type=82,
            ict_index_rank=144,
            ict_index_rank_type=37,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.01,
            saves_per_90=0.0,
            expected_assists_per_90=0.08,
            expected_goal_involvements_per_90=0.09,
            expected_goals_conceded_per_90=1.13,
            goals_conceded_per_90=1.19,
            now_cost_rank=249,
            now_cost_rank_type=27,
            form_rank=139,
            form_rank_type=34,
            points_per_game_rank=53,
            points_per_game_rank_type=8,
            selected_rank=28,
            selected_rank_type=10,
            starts_per_90=1.05,
            clean_sheets_per_90=0.35,
            position="Defender",
        ),
        3: PlayerDetail(
            chance_of_playing_next_round=75,
            chance_of_playing_this_round=75,
            code=226597,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=2,
            cost_change_start_fall=-2,
            dreamteam_count=2,
            element_type=2,
            ep_next="3.3",
            ep_this="3.3",
            event_points=0,
            first_name="Gabriel",
            form="3.4",
            id=3,
            in_dreamteam=True,
            news="Muscle injury - 75% chance of playing",
            news_added="2024-11-27T10:30:06.325759Z",
            now_cost=62,
            photo="226597.jpg",
            points_per_game="4.6",
            second_name="dos Santos Magalhães",
            selected_by_percent="24.1",
            special=False,
            squad_number=None,
            status="d",
            team=1,
            team_code=3,
            total_points=60,
            transfers_in=2863617,
            transfers_in_event=18803,
            transfers_out=1795371,
            transfers_out_event=64770,
            value_form="0.5",
            value_season="9.7",
            web_name="Gabriel",
            region=30,
            minutes=1088,
            goals_scored=3,
            assists=1,
            clean_sheets=4,
            goals_conceded=13,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=1,
            red_cards=0,
            saves=0,
            bonus=4,
            bps=210,
            influence="313.4",
            creativity="68.2",
            threat="215.0",
            ict_index="59.7",
            starts=13,
            expected_goals="1.76",
            expected_assists="0.50",
            expected_goal_involvements="2.26",
            expected_goals_conceded="12.50",
            influence_rank=46,
            influence_rank_type=14,
            creativity_rank=215,
            creativity_rank_type=55,
            threat_rank=58,
            threat_rank_type=2,
            ict_index_rank=84,
            ict_index_rank_type=14,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.15,
            saves_per_90=0.0,
            expected_assists_per_90=0.04,
            expected_goal_involvements_per_90=0.19,
            expected_goals_conceded_per_90=1.03,
            goals_conceded_per_90=1.08,
            now_cost_rank=66,
            now_cost_rank_type=3,
            form_rank=75,
            form_rank_type=19,
            points_per_game_rank=30,
            points_per_game_rank_type=4,
            selected_rank=13,
            selected_rank_type=5,
            starts_per_90=1.08,
            clean_sheets_per_90=0.33,
            position="Defender",
        ),
        333: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=441428,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=-6,
            cost_change_start_fall=6,
            dreamteam_count=0,
            element_type=2,
            ep_next="1.2",
            ep_this="0.0",
            event_points=0,
            first_name="Jarell",
            form="0.2",
            id=333,
            in_dreamteam=False,
            news="",
            news_added="2024-08-23T09:30:06.099816Z",
            now_cost=39,
            photo="441428.jpg",
            points_per_game="0.7",
            second_name="Quansah",
            selected_by_percent="1.5",
            special=False,
            squad_number=None,
            status="a",
            team=12,
            team_code=14,
            total_points=2,
            transfers_in=147806,
            transfers_in_event=7721,
            transfers_out=578128,
            transfers_out_event=1694,
            value_form="0.1",
            value_season="0.5",
            web_name="Quansah",
            region=241,
            minutes=152,
            goals_scored=0,
            assists=0,
            clean_sheets=0,
            goals_conceded=3,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=1,
            red_cards=0,
            saves=0,
            bonus=0,
            bps=12,
            influence="41.0",
            creativity="3.0",
            threat="2.0",
            ict_index="4.6",
            starts=2,
            expected_goals="0.00",
            expected_assists="0.12",
            expected_goal_involvements="0.12",
            expected_goals_conceded="2.99",
            influence_rank=351,
            influence_rank_type=124,
            creativity_rank=398,
            creativity_rank_type=138,
            threat_rank=381,
            threat_rank_type=131,
            ict_index_rank=396,
            ict_index_rank_type=134,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.0,
            saves_per_90=0.0,
            expected_assists_per_90=0.07,
            expected_goal_involvements_per_90=0.07,
            expected_goals_conceded_per_90=1.77,
            goals_conceded_per_90=1.78,
            now_cost_rank=686,
            now_cost_rank_type=225,
            form_rank=360,
            form_rank_type=118,
            points_per_game_rank=461,
            points_per_game_rank_type=153,
            selected_rank=170,
            selected_rank_type=68,
            starts_per_90=1.18,
            clean_sheets_per_90=0.0,
            position="Defender",
        ),
        366: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=141746,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=0,
            cost_change_start_fall=0,
            dreamteam_count=2,
            element_type=3,
            ep_next="6.8",
            ep_this="7.8",
            event_points=9,
            first_name="Bruno",
            form="7.8",
            id=366,
            in_dreamteam=False,
            news="",
            news_added="2024-09-29T21:00:06.390627Z",
            now_cost=85,
            photo="141746.jpg",
            points_per_game="4.8",
            second_name="Borges Fernandes",
            selected_by_percent="15.4",
            special=False,
            squad_number=None,
            status="a",
            team=14,
            team_code=1,
            total_points=72,
            transfers_in=1688930,
            transfers_in_event=14677,
            transfers_out=2030421,
            transfers_out_event=37747,
            value_form="0.9",
            value_season="8.5",
            web_name="B.Fernandes",
            region=173,
            minutes=1249,
            goals_scored=3,
            assists=6,
            clean_sheets=6,
            goals_conceded=17,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=1,
            red_cards=1,
            saves=0,
            bonus=8,
            bps=313,
            influence="374.4",
            creativity="458.1",
            threat="236.0",
            ict_index="106.6",
            starts=15,
            expected_goals="4.42",
            expected_assists="2.72",
            expected_goal_involvements="7.14",
            expected_goals_conceded="18.96",
            influence_rank=20,
            influence_rank_type=7,
            creativity_rank=8,
            creativity_rank_type=7,
            threat_rank=50,
            threat_rank_type=31,
            ict_index_rank=13,
            ict_index_rank_type=10,
            corners_and_indirect_freekicks_order=2,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=1,
            direct_freekicks_text="",
            penalties_order=1,
            penalties_text="",
            expected_goals_per_90=0.32,
            saves_per_90=0.0,
            expected_assists_per_90=0.2,
            expected_goal_involvements_per_90=0.52,
            expected_goals_conceded_per_90=1.37,
            goals_conceded_per_90=1.22,
            now_cost_rank=9,
            now_cost_rank_type=7,
            form_rank=3,
            form_rank_type=3,
            points_per_game_rank=25,
            points_per_game_rank_type=12,
            selected_rank=25,
            selected_rank_type=8,
            starts_per_90=1.08,
            clean_sheets_per_90=0.43,
            position="Midfielder",
        ),
        317: PlayerDetail(
            chance_of_playing_next_round=25,
            chance_of_playing_this_round=25,
            code=194634,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=-3,
            cost_change_start_fall=3,
            dreamteam_count=0,
            element_type=3,
            ep_next="0.2",
            ep_this="0.0",
            event_points=0,
            first_name="Diogo",
            form="0.0",
            id=317,
            in_dreamteam=False,
            news="Rib Injury - 25% chance of playing",
            news_added="2024-10-20T21:30:07.041173Z",
            now_cost=72,
            photo="194634.jpg",
            points_per_game="5.0",
            second_name="Teixeira da Silva",
            selected_by_percent="2.7",
            special=False,
            squad_number=None,
            status="d",
            team=12,
            team_code=14,
            total_points=35,
            transfers_in=1023083,
            transfers_in_event=85,
            transfers_out=2409388,
            transfers_out_event=2348,
            value_form="0.0",
            value_season="4.9",
            web_name="Diogo J.",
            region=173,
            minutes=492,
            goals_scored=2,
            assists=3,
            clean_sheets=4,
            goals_conceded=1,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=1,
            red_cards=0,
            saves=0,
            bonus=1,
            bps=85,
            influence="105.0",
            creativity="55.1",
            threat="157.0",
            ict_index="31.6",
            starts=7,
            expected_goals="2.72",
            expected_assists="0.32",
            expected_goal_involvements="3.04",
            expected_goals_conceded="3.14",
            influence_rank=253,
            influence_rank_type=109,
            creativity_rank=248,
            creativity_rank_type=153,
            threat_rank=97,
            threat_rank_type=62,
            ict_index_rank=209,
            ict_index_rank_type=106,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.5,
            saves_per_90=0.0,
            expected_assists_per_90=0.06,
            expected_goal_involvements_per_90=0.56,
            expected_goals_conceded_per_90=0.57,
            goals_conceded_per_90=0.18,
            now_cost_rank=20,
            now_cost_rank_type=13,
            form_rank=691,
            form_rank_type=314,
            points_per_game_rank=20,
            points_per_game_rank_type=10,
            selected_rank=113,
            selected_rank_type=34,
            starts_per_90=1.28,
            clean_sheets_per_90=0.73,
            position="Midfielder",
        ),
        54: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=244850,
            cost_change_event=1,
            cost_change_event_fall=-1,
            cost_change_start=4,
            cost_change_start_fall=-4,
            dreamteam_count=1,
            element_type=3,
            ep_next="3.0",
            ep_this="3.5",
            event_points=2,
            first_name="Morgan",
            form="3.0",
            id=54,
            in_dreamteam=False,
            news="",
            news_added="2024-11-04T00:00:07.298201Z",
            now_cost=54,
            photo="244850.jpg",
            points_per_game="3.9",
            second_name="Rogers",
            selected_by_percent="22.1",
            special=False,
            squad_number=None,
            status="a",
            team=2,
            team_code=7,
            total_points=59,
            transfers_in=2963824,
            transfers_in_event=14253,
            transfers_out=1495974,
            transfers_out_event=27458,
            value_form="0.6",
            value_season="10.9",
            web_name="Rogers",
            region=241,
            minutes=1221,
            goals_scored=4,
            assists=2,
            clean_sheets=2,
            goals_conceded=17,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=4,
            red_cards=0,
            saves=0,
            bonus=6,
            bps=195,
            influence="277.2",
            creativity="316.0",
            threat="271.0",
            ict_index="86.6",
            starts=15,
            expected_goals="3.09",
            expected_assists="2.41",
            expected_goal_involvements="5.50",
            expected_goals_conceded="14.45",
            influence_rank=74,
            influence_rank_type=25,
            creativity_rank=32,
            creativity_rank_type=27,
            threat_rank=41,
            threat_rank_type=25,
            ict_index_rank=32,
            ict_index_rank_type=22,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.23,
            saves_per_90=0.0,
            expected_assists_per_90=0.18,
            expected_goal_involvements_per_90=0.41,
            expected_goals_conceded_per_90=1.07,
            goals_conceded_per_90=1.25,
            now_cost_rank=137,
            now_cost_rank_type=81,
            form_rank=96,
            form_rank_type=47,
            points_per_game_rank=55,
            points_per_game_rank_type=26,
            selected_rank=16,
            selected_rank_type=5,
            starts_per_90=1.11,
            clean_sheets_per_90=0.15,
            position="Midfielder",
        ),
        17: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=223340,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=5,
            cost_change_start_fall=-5,
            dreamteam_count=4,
            element_type=3,
            ep_next="8.6",
            ep_this="8.6",
            event_points=2,
            first_name="Bukayo",
            form="7.6",
            id=17,
            in_dreamteam=True,
            news="",
            news_added="2024-11-10T23:00:07.191683Z",
            now_cost=105,
            photo="223340.jpg",
            points_per_game="7.4",
            second_name="Saka",
            selected_by_percent="42.6",
            special=False,
            squad_number=None,
            status="a",
            team=1,
            team_code=3,
            total_points=103,
            transfers_in=4816634,
            transfers_in_event=53627,
            transfers_out=3550793,
            transfers_out_event=20967,
            value_form="0.7",
            value_season="9.8",
            web_name="Saka",
            region=241,
            minutes=1155,
            goals_scored=5,
            assists=11,
            clean_sheets=5,
            goals_conceded=12,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=3,
            red_cards=0,
            saves=0,
            bonus=16,
            bps=409,
            influence="493.4",
            creativity="580.6",
            threat="561.0",
            ict_index="163.4",
            starts=14,
            expected_goals="3.85",
            expected_assists="5.04",
            expected_goal_involvements="8.89",
            expected_goals_conceded="9.67",
            influence_rank=7,
            influence_rank_type=4,
            creativity_rank=1,
            creativity_rank_type=1,
            threat_rank=4,
            threat_rank_type=2,
            ict_index_rank=3,
            ict_index_rank_type=3,
            corners_and_indirect_freekicks_order=1,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=1,
            penalties_text="",
            expected_goals_per_90=0.3,
            saves_per_90=0.0,
            expected_assists_per_90=0.39,
            expected_goal_involvements_per_90=0.69,
            expected_goals_conceded_per_90=0.75,
            goals_conceded_per_90=0.94,
            now_cost_rank=4,
            now_cost_rank_type=3,
            form_rank=4,
            form_rank_type=4,
            points_per_game_rank=3,
            points_per_game_rank_type=3,
            selected_rank=4,
            selected_rank_type=3,
            starts_per_90=1.09,
            clean_sheets_per_90=0.39,
            position="Midfielder",
        ),
        351: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=223094,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=0,
            cost_change_start_fall=0,
            dreamteam_count=3,
            element_type=4,
            ep_next="5.2",
            ep_this="5.2",
            event_points=7,
            first_name="Erling",
            form="4.2",
            id=351,
            in_dreamteam=True,
            news="",
            news_added="2024-09-13T15:00:06.985607Z",
            now_cost=150,
            photo="223094.jpg",
            points_per_game="6.5",
            second_name="Haaland",
            selected_by_percent="42.9",
            special=False,
            squad_number=None,
            status="a",
            team=13,
            team_code=43,
            total_points=98,
            transfers_in=2823210,
            transfers_in_event=4595,
            transfers_out=3964334,
            transfers_out_event=69869,
            value_form="0.3",
            value_season="6.5",
            web_name="Haaland",
            region=161,
            minutes=1349,
            goals_scored=13,
            assists=1,
            clean_sheets=3,
            goals_conceded=21,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=2,
            red_cards=0,
            saves=0,
            bonus=15,
            bps=438,
            influence="527.4",
            creativity="142.1",
            threat="908.0",
            ict_index="158.0",
            starts=15,
            expected_goals="12.85",
            expected_assists="0.86",
            expected_goal_involvements="13.71",
            expected_goals_conceded="21.56",
            influence_rank=4,
            influence_rank_type=1,
            creativity_rank=125,
            creativity_rank_type=11,
            threat_rank=1,
            threat_rank_type=1,
            ict_index_rank=4,
            ict_index_rank_type=1,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=3,
            direct_freekicks_text="",
            penalties_order=1,
            penalties_text="",
            expected_goals_per_90=0.86,
            saves_per_90=0.0,
            expected_assists_per_90=0.06,
            expected_goal_involvements_per_90=0.92,
            expected_goals_conceded_per_90=1.44,
            goals_conceded_per_90=1.4,
            now_cost_rank=1,
            now_cost_rank_type=1,
            form_rank=41,
            form_rank_type=10,
            points_per_game_rank=4,
            points_per_game_rank_type=1,
            selected_rank=3,
            selected_rank_type=1,
            starts_per_90=1.0,
            clean_sheets_per_90=0.2,
            position="Forward",
        ),
        401: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=219168,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=0,
            cost_change_start_fall=0,
            dreamteam_count=0,
            element_type=4,
            ep_next="6.6",
            ep_this="6.6",
            event_points=8,
            first_name="Alexander",
            form="6.6",
            id=401,
            in_dreamteam=False,
            news="",
            news_added="2024-11-30T22:00:07.827670Z",
            now_cost=85,
            photo="219168.jpg",
            points_per_game="5.3",
            second_name="Isak",
            selected_by_percent="19.3",
            special=False,
            squad_number=None,
            status="a",
            team=15,
            team_code=4,
            total_points=69,
            transfers_in=2014567,
            transfers_in_event=111292,
            transfers_out=5713078,
            transfers_out_event=4964,
            value_form="0.8",
            value_season="8.1",
            web_name="Isak",
            region=206,
            minutes=1056,
            goals_scored=6,
            assists=3,
            clean_sheets=2,
            goals_conceded=19,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=0,
            red_cards=0,
            saves=0,
            bonus=12,
            bps=251,
            influence="312.6",
            creativity="229.8",
            threat="413.0",
            ict_index="94.9",
            starts=13,
            expected_goals="5.59",
            expected_assists="1.78",
            expected_goal_involvements="7.37",
            expected_goals_conceded="16.75",
            influence_rank=48,
            influence_rank_type=7,
            creativity_rank=59,
            creativity_rank_type=2,
            threat_rank=15,
            threat_rank_type=9,
            ict_index_rank=24,
            ict_index_rank_type=5,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=3,
            direct_freekicks_text="",
            penalties_order=2,
            penalties_text="",
            expected_goals_per_90=0.48,
            saves_per_90=0.0,
            expected_assists_per_90=0.15,
            expected_goal_involvements_per_90=0.63,
            expected_goals_conceded_per_90=1.43,
            goals_conceded_per_90=1.62,
            now_cost_rank=10,
            now_cost_rank_type=3,
            form_rank=11,
            form_rank_type=1,
            points_per_game_rank=12,
            points_per_game_rank_type=7,
            selected_rank=21,
            selected_rank_type=7,
            starts_per_90=1.11,
            clean_sheets_per_90=0.17,
            position="Forward",
        ),
        82: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=154566,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=0,
            cost_change_start_fall=0,
            dreamteam_count=1,
            element_type=4,
            ep_next="4.2",
            ep_this="3.2",
            event_points=7,
            first_name="Dominic",
            form="3.2",
            id=82,
            in_dreamteam=False,
            news="",
            news_added="2024-12-02T00:00:07.868049Z",
            now_cost=75,
            photo="154566.jpg",
            points_per_game="4.8",
            second_name="Solanke-Mitchell",
            selected_by_percent="8.6",
            special=False,
            squad_number=None,
            status="a",
            team=18,
            team_code=6,
            total_points=57,
            transfers_in=2065073,
            transfers_in_event=11177,
            transfers_out=3920261,
            transfers_out_event=12187,
            value_form="0.4",
            value_season="7.6",
            web_name="Solanke",
            region=241,
            minutes=1067,
            goals_scored=5,
            assists=3,
            clean_sheets=2,
            goals_conceded=16,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=0,
            red_cards=0,
            saves=0,
            bonus=4,
            bps=233,
            influence="291.4",
            creativity="128.6",
            threat="417.0",
            ict_index="83.6",
            starts=12,
            expected_goals="6.77",
            expected_assists="0.70",
            expected_goal_involvements="7.47",
            expected_goals_conceded="18.80",
            influence_rank=61,
            influence_rank_type=9,
            creativity_rank=144,
            creativity_rank_type=16,
            threat_rank=12,
            threat_rank_type=6,
            ict_index_rank=35,
            ict_index_rank_type=9,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.57,
            saves_per_90=0.0,
            expected_assists_per_90=0.06,
            expected_goal_involvements_per_90=0.63,
            expected_goals_conceded_per_90=1.59,
            goals_conceded_per_90=1.35,
            now_cost_rank=16,
            now_cost_rank_type=6,
            form_rank=89,
            form_rank_type=18,
            points_per_game_rank=24,
            points_per_game_rank_type=10,
            selected_rank=46,
            selected_rank_type=11,
            starts_per_90=1.01,
            clean_sheets_per_90=0.17,
            position="Forward",
        ),
        536: PlayerDetail(
            chance_of_playing_next_round=None,
            chance_of_playing_this_round=None,
            code=79602,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=0,
            cost_change_start_fall=0,
            dreamteam_count=0,
            element_type=1,
            ep_next="0.0",
            ep_this="0.0",
            event_points=0,
            first_name="Daniel",
            form="0.0",
            id=536,
            in_dreamteam=False,
            news="",
            news_added=None,
            now_cost=40,
            photo="79602.jpg",
            points_per_game="0.0",
            second_name="Bentley",
            selected_by_percent="1.5",
            special=False,
            squad_number=None,
            status="a",
            team=20,
            team_code=39,
            total_points=0,
            transfers_in=51660,
            transfers_in_event=157,
            transfers_out=108742,
            transfers_out_event=537,
            value_form="0.0",
            value_season="0.0",
            web_name="Bentley",
            region=241,
            minutes=0,
            goals_scored=0,
            assists=0,
            clean_sheets=0,
            goals_conceded=0,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=0,
            red_cards=0,
            saves=0,
            bonus=0,
            bps=0,
            influence="0.0",
            creativity="0.0",
            threat="0.0",
            ict_index="0.0",
            starts=0,
            expected_goals="0.00",
            expected_assists="0.00",
            expected_goal_involvements="0.00",
            expected_goals_conceded="0.00",
            influence_rank=480,
            influence_rank_type=42,
            creativity_rank=457,
            creativity_rank_type=18,
            threat_rank=419,
            threat_rank_type=9,
            ict_index_rank=482,
            ict_index_rank_type=42,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.0,
            saves_per_90=0.0,
            expected_assists_per_90=0.0,
            expected_goal_involvements_per_90=0.0,
            expected_goals_conceded_per_90=0.0,
            goals_conceded_per_90=0.0,
            now_cost_rank=593,
            now_cost_rank_type=45,
            form_rank=415,
            form_rank_type=33,
            points_per_game_rank=485,
            points_per_game_rank_type=42,
            selected_rank=169,
            selected_rank_type=23,
            starts_per_90=0.0,
            clean_sheets_per_90=0.0,
            position="Goalkeeper",
        ),
        19: PlayerDetail(
            chance_of_playing_next_round=None,
            chance_of_playing_this_round=None,
            code=209289,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=1,
            cost_change_start_fall=-1,
            dreamteam_count=1,
            element_type=3,
            ep_next="2.4",
            ep_this="2.4",
            event_points=1,
            first_name="Emile",
            form="3.4",
            id=19,
            in_dreamteam=False,
            news="",
            news_added=None,
            now_cost=56,
            photo="209289.jpg",
            points_per_game="4.0",
            second_name="Smith Rowe",
            selected_by_percent="20.7",
            special=False,
            squad_number=None,
            status="a",
            team=9,
            team_code=54,
            total_points=60,
            transfers_in=3367982,
            transfers_in_event=4010,
            transfers_out=2856783,
            transfers_out_event=62538,
            value_form="0.6",
            value_season="10.7",
            web_name="Smith Rowe",
            region=241,
            minutes=1067,
            goals_scored=3,
            assists=2,
            clean_sheets=5,
            goals_conceded=13,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=1,
            red_cards=0,
            saves=0,
            bonus=8,
            bps=247,
            influence="245.4",
            creativity="244.2",
            threat="164.0",
            ict_index="65.4",
            starts=14,
            expected_goals="2.12",
            expected_assists="1.27",
            expected_goal_involvements="3.39",
            expected_goals_conceded="13.00",
            influence_rank=98,
            influence_rank_type=33,
            creativity_rank=52,
            creativity_rank_type=43,
            threat_rank=92,
            threat_rank_type=58,
            ict_index_rank=68,
            ict_index_rank_type=43,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.18,
            saves_per_90=0.0,
            expected_assists_per_90=0.11,
            expected_goal_involvements_per_90=0.29,
            expected_goals_conceded_per_90=1.1,
            goals_conceded_per_90=1.1,
            now_cost_rank=99,
            now_cost_rank_type=63,
            form_rank=72,
            form_rank_type=33,
            points_per_game_rank=49,
            points_per_game_rank_type=22,
            selected_rank=19,
            selected_rank_type=6,
            starts_per_90=1.18,
            clean_sheets_per_90=0.42,
            position="Midfielder",
        ),
        255: PlayerDetail(
            chance_of_playing_next_round=None,
            chance_of_playing_this_round=None,
            code=169528,
            cost_change_event=0,
            cost_change_event_fall=0,
            cost_change_start=2,
            cost_change_start_fall=-2,
            dreamteam_count=0,
            element_type=2,
            ep_next="2.0",
            ep_this="2.0",
            event_points=1,
            first_name="Antonee",
            form="3.0",
            id=255,
            in_dreamteam=False,
            news="",
            news_added=None,
            now_cost=47,
            photo="169528.jpg",
            points_per_game="3.3",
            second_name="Robinson",
            selected_by_percent="15.3",
            special=False,
            squad_number=None,
            status="a",
            team=9,
            team_code=54,
            total_points=49,
            transfers_in=1830857,
            transfers_in_event=8371,
            transfers_out=1167987,
            transfers_out_event=14338,
            value_form="0.6",
            value_season="10.4",
            web_name="Robinson",
            region=229,
            minutes=1350,
            goals_scored=0,
            assists=4,
            clean_sheets=2,
            goals_conceded=20,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=2,
            red_cards=0,
            saves=0,
            bonus=5,
            bps=215,
            influence="376.6",
            creativity="242.2",
            threat="77.0",
            ict_index="69.8",
            starts=15,
            expected_goals="0.29",
            expected_assists="1.59",
            expected_goal_involvements="1.88",
            expected_goals_conceded="17.98",
            influence_rank=19,
            influence_rank_type=5,
            creativity_rank=54,
            creativity_rank_type=9,
            threat_rank=184,
            threat_rank_type=41,
            ict_index_rank=55,
            ict_index_rank_type=6,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.02,
            saves_per_90=0.0,
            expected_assists_per_90=0.11,
            expected_goal_involvements_per_90=0.13,
            expected_goals_conceded_per_90=1.2,
            goals_conceded_per_90=1.33,
            now_cost_rank=329,
            now_cost_rank_type=41,
            form_rank=91,
            form_rank_type=23,
            points_per_game_rank=87,
            points_per_game_rank_type=18,
            selected_rank=26,
            selected_rank_type=8,
            starts_per_90=1.0,
            clean_sheets_per_90=0.13,
            position="Defender",
        ),
        275: PlayerDetail(
            chance_of_playing_next_round=100,
            chance_of_playing_this_round=100,
            code=222018,
            cost_change_event=-1,
            cost_change_event_fall=1,
            cost_change_start=-1,
            cost_change_start_fall=1,
            dreamteam_count=0,
            element_type=2,
            ep_next="0.4",
            ep_this="0.4",
            event_points=1,
            first_name="Ben",
            form="0.4",
            id=275,
            in_dreamteam=False,
            news="",
            news_added="2024-11-25T09:30:07.489482Z",
            now_cost=39,
            photo="222018.jpg",
            points_per_game="1.1",
            second_name="Johnson",
            selected_by_percent="1.8",
            special=False,
            squad_number=None,
            status="a",
            team=10,
            team_code=40,
            total_points=8,
            transfers_in=206324,
            transfers_in_event=5067,
            transfers_out=379235,
            transfers_out_event=974,
            value_form="0.1",
            value_season="2.1",
            web_name="Johnson",
            region=241,
            minutes=491,
            goals_scored=0,
            assists=1,
            clean_sheets=0,
            goals_conceded=14,
            own_goals=0,
            penalties_saved=0,
            penalties_missed=0,
            yellow_cards=1,
            red_cards=0,
            saves=0,
            bonus=0,
            bps=20,
            influence="112.0",
            creativity="45.4",
            threat="11.0",
            ict_index="16.9",
            starts=5,
            expected_goals="0.04",
            expected_assists="0.24",
            expected_goal_involvements="0.28",
            expected_goals_conceded="15.79",
            influence_rank=245,
            influence_rank_type=93,
            creativity_rank=273,
            creativity_rank_type=76,
            threat_rank=329,
            threat_rank_type=108,
            ict_index_rank=295,
            ict_index_rank_type=96,
            corners_and_indirect_freekicks_order=None,
            corners_and_indirect_freekicks_text="",
            direct_freekicks_order=None,
            direct_freekicks_text="",
            penalties_order=None,
            penalties_text="",
            expected_goals_per_90=0.01,
            saves_per_90=0.0,
            expected_assists_per_90=0.04,
            expected_goal_involvements_per_90=0.05,
            expected_goals_conceded_per_90=2.89,
            goals_conceded_per_90=2.57,
            now_cost_rank=683,
            now_cost_rank_type=223,
            form_rank=326,
            form_rank_type=99,
            points_per_game_rank=365,
            points_per_game_rank_type=118,
            selected_rank=148,
            selected_rank_type=57,
            starts_per_90=0.92,
            clean_sheets_per_90=0.0,
            position="Defender",
        ),
    }
