"""Fixtures for tests."""

import pytest


@pytest.fixture
def fixture_data():
    """Fixture for player fixture data."""
    return {
        "id": 1,
        "code": 100,
        "team_h": 1,
        "team_h_score": 2,
        "team_a": 2,
        "team_a_score": 1,
        "event": 1,
        "finished": True,
        "minutes": 90,
        "provisional_start_time": False,
        "kickoff_time": "2023-10-01T12:30:00Z",
        "event_name": "Gameweek 1",
        "is_home": True,
        "difficulty": 3,
    }


@pytest.fixture
def history_data():
    """Fixture for current season data"""
    return {
        "element": 1,
        "fixture": 1,
        "opponent_team": 2,
        "total_points": 10,
        "was_home": True,
        "kickoff_time": "2023-10-01T12:30:00Z",
        "team_h_score": 2,
        "team_a_score": 1,
        "round": 1,
        "minutes": 90,
        "goals_scored": 1,
        "assists": 1,
        "clean_sheets": 1,
        "goals_conceded": 0,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "saves": 0,
        "bonus": 3,
        "bps": 30,
        "influence": "100.0",
        "creativity": "50.0",
        "threat": "75.0",
        "ict_index": "225.0",
        "starts": 1,
        "expected_goals": "0.5",
        "expected_assists": "0.3",
        "expected_goal_involvements": "0.8",
        "expected_goals_conceded": "0.2",
        "value": 100,
        "transfers_balance": 10,
        "selected": 1000,
        "transfers_in": 50,
        "transfers_out": 40,
    }


@pytest.fixture
def history_past_data():
    """Fixture for past season data data."""
    return {
        "season_name": "2022/23",
        "element_code": 1,
        "start_cost": 100,
        "end_cost": 110,
        "total_points": 200,
        "minutes": 3000,
        "goals_scored": 20,
        "assists": 10,
        "clean_sheets": 15,
        "goals_conceded": 25,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 1,
        "yellow_cards": 3,
        "red_cards": 0,
        "saves": 0,
        "bonus": 30,
        "bps": 300,
        "influence": "500.0",
        "creativity": "200.0",
        "threat": "300.0",
        "ict_index": "1000.0",
        "starts": 35,
        "expected_goals": "10.0",
        "expected_assists": "5.0",
        "expected_goal_involvements": "15.0",
        "expected_goals_conceded": "20.0",
    }


@pytest.fixture
def player_detail_data():
    """Fixture for player detail data."""
    return {
        "chance_of_playing_next_round": 0,
        "chance_of_playing_this_round": 0,
        "code": 438098,
        "cost_change_event": 0,
        "cost_change_event_fall": 0,
        "cost_change_start": -1,
        "cost_change_start_fall": 1,
        "dreamteam_count": 0,
        "element_type": 3,
        "ep_next": "0.0",
        "ep_this": "0.0",
        "event_points": 0,
        "first_name": "Fábio",
        "form": "0.0",
        "id": 1,
        "in_dreamteam": False,
        "news": "Has joined Portuguese side FC Porto on loan for the 2024/25 season",
        "news_added": "2024-08-29T11:06:25.241953Z",
        "now_cost": 54,
        "photo": "438098.jpg",
        "points_per_game": "0.0",
        "second_name": "Ferreira Vieira",
        "selected_by_percent": "0.0",
        "special": False,
        "squad_number": None,
        "status": "u",
        "team": 1,
        "team_code": 3,
        "total_points": 0,
        "transfers_in": 439,
        "transfers_in_event": 0,
        "transfers_out": 2172,
        "transfers_out_event": 664,
        "value_form": "0.0",
        "value_season": "0.0",
        "web_name": "Fábio Vieira",
        "region": None,
        "minutes": 0,
        "goals_scored": 0,
        "assists": 0,
        "clean_sheets": 0,
        "goals_conceded": 0,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "saves": 0,
        "bonus": 0,
        "bps": 0,
        "influence": "0.0",
        "creativity": "0.0",
        "threat": "0.0",
        "ict_index": "0.0",
        "starts": 0,
        "expected_goals": "0.00",
        "expected_assists": "0.00",
        "expected_goal_involvements": "0.00",
        "expected_goals_conceded": "0.00",
        "influence_rank": 628,
        "influence_rank_type": 284,
        "creativity_rank": 627,
        "creativity_rank_type": 286,
        "threat_rank": 617,
        "threat_rank_type": 280,
        "ict_index_rank": 631,
        "ict_index_rank_type": 287,
        "corners_and_indirect_freekicks_order": None,
        "corners_and_indirect_freekicks_text": "",
        "direct_freekicks_order": None,
        "direct_freekicks_text": "",
        "penalties_order": None,
        "penalties_text": "",
        "expected_goals_per_90": 0,
        "saves_per_90": 0,
        "expected_assists_per_90": 0,
        "expected_goal_involvements_per_90": 0,
        "expected_goals_conceded_per_90": 0,
        "goals_conceded_per_90": 0,
        "now_cost_rank": 167,
        "now_cost_rank_type": 104,
        "form_rank": 627,
        "form_rank_type": 286,
        "points_per_game_rank": 627,
        "points_per_game_rank_type": 286,
        "selected_rank": 593,
        "selected_rank_type": 260,
        "starts_per_90": 0,
        "clean_sheets_per_90": 0,
    }


@pytest.fixture
def player_data(fixture_data, history_data, history_past_data):
    return {
        "fixtures": [fixture_data],
        "history": [history_data],
        "history_past": [history_past_data],
    }


@pytest.fixture
def players_bootstrap_data(player_detail_data):
    """Fixture for bootstrap data."""
    return {"elements": [player_detail_data]}


@pytest.fixture
def league_data():
    """Fixture for league data."""
    return {
        "new_entries": {"has_next": False, "page": 1, "results": []},
        "last_updated_data": "2024-09-28T19:49:21Z",
        "league": {
            "id": 1,
            "name": "Arsenal",
            "created": "2024-07-17T11:51:46.252125Z",
            "closed": False,
            "max_entries": None,
            "league_type": "s",
            "scoring": "c",
            "admin_entry": None,
            "start_event": 1,
            "code_privacy": "p",
            "has_cup": True,
            "cup_league": None,
            "rank": None,
        },
        "standings": {
            "has_next": True,
            "page": 1,
            "results": [
                {
                    "id": 46599801,
                    "event_total": 96,
                    "player_name": "Ajdin Selimovic",
                    "rank": 1,
                    "last_rank": 193,
                    "rank_sort": 1,
                    "total": 513,
                    "entry": 5932784,
                    "entry_name": "Ronaldinhovic",
                },
                {
                    "id": 9178578,
                    "event_total": 53,
                    "player_name": "tunjay ozer",
                    "rank": 2,
                    "last_rank": 1,
                    "rank_sort": 2,
                    "total": 508,
                    "entry": 1432938,
                    "entry_name": "yeah buddy",
                },
                {
                    "id": 49695302,
                    "event_total": 72,
                    "player_name": "Khalil Nasreddin",
                    "rank": 3,
                    "last_rank": 46,
                    "rank_sort": 3,
                    "total": 498,
                    "entry": 6139538,
                    "entry_name": "النصر لحمااس",
                },
                {
                    "id": 14428798,
                    "event_total": 48,
                    "player_name": "Youssef Ben Turkia",
                    "rank": 4,
                    "last_rank": 2,
                    "rank_sort": 4,
                    "total": 495,
                    "entry": 2197936,
                    "entry_name": "Selim1925",
                },
                {
                    "id": 3273903,
                    "event_total": 73,
                    "player_name": "دردقي بشيش",
                    "rank": 5,
                    "last_rank": 97,
                    "rank_sort": 5,
                    "total": 494,
                    "entry": 524830,
                    "entry_name": "فانتازي دبنقا",
                },
                {
                    "id": 51752719,
                    "event_total": 58,
                    "player_name": "Al-Hamza Al-Absi",
                    "rank": 6,
                    "last_rank": 18,
                    "rank_sort": 6,
                    "total": 492,
                    "entry": 6309120,
                    "entry_name": "Maestro",
                },
                {
                    "id": 7385956,
                    "event_total": 72,
                    "player_name": "Elwazzan Elwazzan",
                    "rank": 7,
                    "last_rank": 133,
                    "rank_sort": 7,
                    "total": 491,
                    "entry": 1160256,
                    "entry_name": "الوزان",
                },
                {
                    "id": 45590678,
                    "event_total": 85,
                    "player_name": "Sileman Harki",
                    "rank": 8,
                    "last_rank": 834,
                    "rank_sort": 8,
                    "total": 491,
                    "entry": 5863704,
                    "entry_name": "silemankurdi",
                },
                {
                    "id": 21829325,
                    "event_total": 82,
                    "player_name": "Barham Jabara",
                    "rank": 9,
                    "last_rank": 658,
                    "rank_sort": 9,
                    "total": 490,
                    "entry": 3212728,
                    "entry_name": "barham1234",
                },
                {
                    "id": 63953654,
                    "event_total": 70,
                    "player_name": "James Jeffery",
                    "rank": 10,
                    "last_rank": 150,
                    "rank_sort": 10,
                    "total": 488,
                    "entry": 7586446,
                    "entry_name": "Jeffery10 United",
                },
                {
                    "id": 57264230,
                    "event_total": 60,
                    "player_name": "Ibrahim Alamamy",
                    "rank": 11,
                    "last_rank": 23,
                    "rank_sort": 11,
                    "total": 488,
                    "entry": 6875353,
                    "entry_name": "B E M O",
                },
                {
                    "id": 21084873,
                    "event_total": 89,
                    "player_name": "عمر أبوحكيم",
                    "rank": 12,
                    "last_rank": 2485,
                    "rank_sort": 12,
                    "total": 486,
                    "entry": 3113192,
                    "entry_name": "صہٰاحہٰبٰٰ الُِڪوُرة",
                },
                {
                    "id": 61679379,
                    "event_total": 43,
                    "player_name": "Ahmed Ditto",
                    "rank": 13,
                    "last_rank": 5,
                    "rank_sort": 13,
                    "total": 485,
                    "entry": 7350500,
                    "entry_name": "Ditto.FC",
                },
                {
                    "id": 1207293,
                    "event_total": 59,
                    "player_name": "24 JAM",
                    "rank": 14,
                    "last_rank": 26,
                    "rank_sort": 14,
                    "total": 485,
                    "entry": 197639,
                    "entry_name": "Caterpillar",
                },
                {
                    "id": 68754206,
                    "event_total": 46,
                    "player_name": "ahmed khaled",
                    "rank": 15,
                    "last_rank": 8,
                    "rank_sort": 15,
                    "total": 484,
                    "entry": 8076406,
                    "entry_name": "ابوكتف�",
                },
                {
                    "id": 10549293,
                    "event_total": 77,
                    "player_name": "Jan Popelínský",
                    "rank": 16,
                    "last_rank": 432,
                    "rank_sort": 16,
                    "total": 484,
                    "entry": 1636078,
                    "entry_name": "SexyMan",
                },
                {
                    "id": 4228484,
                    "event_total": 64,
                    "player_name": "Nikola Vasić",
                    "rank": 17,
                    "last_rank": 150,
                    "rank_sort": 17,
                    "total": 482,
                    "entry": 673844,
                    "entry_name": "Argoulides",
                },
                {
                    "id": 1873910,
                    "event_total": 85,
                    "player_name": "Salim Suleiman",
                    "rank": 17,
                    "last_rank": 2393,
                    "rank_sort": 18,
                    "total": 482,
                    "entry": 302997,
                    "entry_name": "Gwena FC",
                },
                {
                    "id": 24211267,
                    "event_total": 82,
                    "player_name": "Tiago T",
                    "rank": 19,
                    "last_rank": 1701,
                    "rank_sort": 19,
                    "total": 482,
                    "entry": 3526742,
                    "entry_name": "Tielemans Square1989",
                },
                {
                    "id": 69505316,
                    "event_total": 57,
                    "player_name": "muhammad naim",
                    "rank": 20,
                    "last_rank": 58,
                    "rank_sort": 20,
                    "total": 482,
                    "entry": 8152480,
                    "entry_name": "Arsenal07",
                },
                {
                    "id": 14771159,
                    "event_total": 55,
                    "player_name": "Yonael Afework",
                    "rank": 21,
                    "last_rank": 45,
                    "rank_sort": 21,
                    "total": 482,
                    "entry": 2246314,
                    "entry_name": "yonaellll",
                },
                {
                    "id": 16507214,
                    "event_total": 64,
                    "player_name": "Erik Pettersson",
                    "rank": 22,
                    "last_rank": 176,
                    "rank_sort": 22,
                    "total": 481,
                    "entry": 2489812,
                    "entry_name": "FC Bendtnerlona",
                },
                {
                    "id": 10793269,
                    "event_total": 47,
                    "player_name": "Kye Calvy",
                    "rank": 23,
                    "last_rank": 22,
                    "rank_sort": 23,
                    "total": 480,
                    "entry": 1670842,
                    "entry_name": "CUCU CUCURELLA",
                },
                {
                    "id": 8888216,
                    "event_total": 61,
                    "player_name": "Hashem ZR",
                    "rank": 24,
                    "last_rank": 139,
                    "rank_sort": 24,
                    "total": 480,
                    "entry": 1388490,
                    "entry_name": "HashemZr",
                },
                {
                    "id": 26830106,
                    "event_total": 49,
                    "player_name": "Hridesh Wagle",
                    "rank": 25,
                    "last_rank": 7,
                    "rank_sort": 25,
                    "total": 480,
                    "entry": 3860569,
                    "entry_name": "GoodBoy Gunner �",
                },
                {
                    "id": 48513986,
                    "event_total": 64,
                    "player_name": "Sayed Ali",
                    "rank": 26,
                    "last_rank": 243,
                    "rank_sort": 26,
                    "total": 479,
                    "entry": 6053249,
                    "entry_name": "قلب البابا",
                },
                {
                    "id": 46933185,
                    "event_total": 50,
                    "player_name": "rebin ali",
                    "rank": 27,
                    "last_rank": 32,
                    "rank_sort": 27,
                    "total": 479,
                    "entry": 5953948,
                    "entry_name": "shery fantasy",
                },
                {
                    "id": 37522503,
                    "event_total": 56,
                    "player_name": "nyamwanga boy",
                    "rank": 27,
                    "last_rank": 75,
                    "rank_sort": 28,
                    "total": 479,
                    "entry": 5135935,
                    "entry_name": "TANZANIA  1",
                },
                {
                    "id": 8574633,
                    "event_total": 74,
                    "player_name": "Benny Angeles",
                    "rank": 27,
                    "last_rank": 932,
                    "rank_sort": 29,
                    "total": 479,
                    "entry": 1340247,
                    "entry_name": "115 Charges FC",
                },
                {
                    "id": 11871468,
                    "event_total": 77,
                    "player_name": "Andy Neale",
                    "rank": 30,
                    "last_rank": 819,
                    "rank_sort": 30,
                    "total": 479,
                    "entry": 1826126,
                    "entry_name": "Arteta's Vision",
                },
                {
                    "id": 10559941,
                    "event_total": 61,
                    "player_name": "Paul Abbott",
                    "rank": 31,
                    "last_rank": 176,
                    "rank_sort": 31,
                    "total": 478,
                    "entry": 1637688,
                    "entry_name": "Roaring Wild Shins",
                },
                {
                    "id": 46755814,
                    "event_total": 68,
                    "player_name": "upi 0opah",
                    "rank": 32,
                    "last_rank": 494,
                    "rank_sort": 32,
                    "total": 478,
                    "entry": 5942818,
                    "entry_name": "elweskheen",
                },
                {
                    "id": 25672458,
                    "event_total": 75,
                    "player_name": "Terry Khawaja",
                    "rank": 32,
                    "last_rank": 1199,
                    "rank_sort": 33,
                    "total": 478,
                    "entry": 3710566,
                    "entry_name": "Bad boys for life",
                },
                {
                    "id": 62880879,
                    "event_total": 54,
                    "player_name": "Stergios Andreoglou",
                    "rank": 34,
                    "last_rank": 65,
                    "rank_sort": 34,
                    "total": 478,
                    "entry": 7475598,
                    "entry_name": "Gunners 21",
                },
                {
                    "id": 45460069,
                    "event_total": 77,
                    "player_name": "Ahmed Ali",
                    "rank": 34,
                    "last_rank": 1507,
                    "rank_sort": 35,
                    "total": 478,
                    "entry": 5855477,
                    "entry_name": "2الزنجي المعجزه",
                },
                {
                    "id": 29454720,
                    "event_total": 70,
                    "player_name": "Ahmed Madkour",
                    "rank": 36,
                    "last_rank": 740,
                    "rank_sort": 36,
                    "total": 477,
                    "entry": 4131524,
                    "entry_name": "HOBI",
                },
                {
                    "id": 32714067,
                    "event_total": 88,
                    "player_name": "Adam Brismo",
                    "rank": 36,
                    "last_rank": 5639,
                    "rank_sort": 37,
                    "total": 477,
                    "entry": 4548098,
                    "entry_name": "HeMan",
                },
                {
                    "id": 53769495,
                    "event_total": 61,
                    "player_name": "Paul Ovens",
                    "rank": 38,
                    "last_rank": 224,
                    "rank_sort": 38,
                    "total": 477,
                    "entry": 6502948,
                    "entry_name": "haven’tgotimeforthis",
                },
                {
                    "id": 1975973,
                    "event_total": 73,
                    "player_name": "Karan Vir Negi",
                    "rank": 38,
                    "last_rank": 1066,
                    "rank_sort": 39,
                    "total": 477,
                    "entry": 319175,
                    "entry_name": "Old Havertz Kai Hard",
                },
                {
                    "id": 56125796,
                    "event_total": 82,
                    "player_name": "Augustine Ebubeogu",
                    "rank": 38,
                    "last_rank": 3016,
                    "rank_sort": 40,
                    "total": 477,
                    "entry": 6753586,
                    "entry_name": "Stinelee",
                },
                {
                    "id": 17870856,
                    "event_total": 85,
                    "player_name": "David Jones",
                    "rank": 38,
                    "last_rank": 4145,
                    "rank_sort": 41,
                    "total": 477,
                    "entry": 2679834,
                    "entry_name": "Djibouti FC",
                },
                {
                    "id": 53553071,
                    "event_total": 60,
                    "player_name": "Sam Callcut",
                    "rank": 42,
                    "last_rank": 193,
                    "rank_sort": 42,
                    "total": 477,
                    "entry": 6479949,
                    "entry_name": "Saka White Rice",
                },
                {
                    "id": 27814024,
                    "event_total": 66,
                    "player_name": "Abdulio .",
                    "rank": 42,
                    "last_rank": 432,
                    "rank_sort": 43,
                    "total": 477,
                    "entry": 3945686,
                    "entry_name": "King Kai",
                },
                {
                    "id": 14154386,
                    "event_total": 57,
                    "player_name": "James Morris",
                    "rank": 44,
                    "last_rank": 133,
                    "rank_sort": 44,
                    "total": 476,
                    "entry": 2156730,
                    "entry_name": "Jim's Janglies",
                },
                {
                    "id": 4658691,
                    "event_total": 66,
                    "player_name": "Yehia 🇪🇬🇵🇸",
                    "rank": 44,
                    "last_rank": 480,
                    "rank_sort": 45,
                    "total": 476,
                    "entry": 741337,
                    "entry_name": "Yehia",
                },
                {
                    "id": 30139986,
                    "event_total": 57,
                    "player_name": "Louie Heron",
                    "rank": 46,
                    "last_rank": 133,
                    "rank_sort": 46,
                    "total": 476,
                    "entry": 4216381,
                    "entry_name": "Mosgiel Metapods",
                },
                {
                    "id": 51066576,
                    "event_total": 92,
                    "player_name": "yassin zakaria",
                    "rank": 46,
                    "last_rank": 9876,
                    "rank_sort": 47,
                    "total": 476,
                    "entry": 6261743,
                    "entry_name": "yassinzakaria",
                },
                {
                    "id": 61203460,
                    "event_total": 83,
                    "player_name": "Yahia Ltf",
                    "rank": 48,
                    "last_rank": 4145,
                    "rank_sort": 48,
                    "total": 475,
                    "entry": 7299374,
                    "entry_name": "Quelle BUT",
                },
                {
                    "id": 3139680,
                    "event_total": 54,
                    "player_name": "Mohamed Ali",
                    "rank": 49,
                    "last_rank": 100,
                    "rank_sort": 49,
                    "total": 475,
                    "entry": 503352,
                    "entry_name": "Three (A)",
                },
                {
                    "id": 12261491,
                    "event_total": 56,
                    "player_name": "Alex Scofield",
                    "rank": 49,
                    "last_rank": 130,
                    "rank_sort": 50,
                    "total": 475,
                    "entry": 1883694,
                    "entry_name": "Scözil XI",
                },
            ],
        },
    }


@pytest.fixture
def picks_data_no_chip():
    return {
        "active_chip": None,
        "automatic_subs": [],
        "entry_history": {
            "event": 1,
            "points": 54,
            "total_points": 54,
            "rank": 5141847,
            "rank_sort": 5141847,
            "overall_rank": 5141845,
            "percentile_rank": 60,
            "bank": 5,
            "value": 1000,
            "event_transfers": 0,
            "event_transfers_cost": 0,
            "points_on_bench": 5,
        },
        "picks": [
            {
                "element": 201,
                "position": 1,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 422,
                "position": 2,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 3,
                "position": 3,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 333,
                "position": 4,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 366,
                "position": 5,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 317,
                "position": 6,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 54,
                "position": 7,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 17,
                "position": 8,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": True,
            },
            {
                "element": 351,
                "position": 9,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 401,
                "position": 10,
                "multiplier": 2,
                "is_captain": True,
                "is_vice_captain": False,
            },
            {
                "element": 82,
                "position": 11,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 536,
                "position": 12,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 19,
                "position": 13,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 255,
                "position": 14,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 275,
                "position": 15,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
        ],
    }


@pytest.fixture
def picks_data_wildcard():
    return {
        "active_chip": "wildcard",
        "automatic_subs": [],
        "entry_history": {
            "event": 1,
            "points": 54,
            "total_points": 54,
            "rank": 5141847,
            "rank_sort": 5141847,
            "overall_rank": 5141845,
            "percentile_rank": 60,
            "bank": 5,
            "value": 1000,
            "event_transfers": 0,
            "event_transfers_cost": 0,
            "points_on_bench": 5,
        },
        "picks": [
            {
                "element": 201,
                "position": 1,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 422,
                "position": 2,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 3,
                "position": 3,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 333,
                "position": 4,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 366,
                "position": 5,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 317,
                "position": 6,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 54,
                "position": 7,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 17,
                "position": 8,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": True,
            },
            {
                "element": 351,
                "position": 9,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 401,
                "position": 10,
                "multiplier": 2,
                "is_captain": True,
                "is_vice_captain": False,
            },
            {
                "element": 82,
                "position": 11,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 536,
                "position": 12,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 19,
                "position": 13,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 255,
                "position": 14,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 275,
                "position": 15,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
        ],
    }


@pytest.fixture
def team_fixture_forest():
    return {
        "code": 17,
        "draw": 0,
        "form": None,
        "id": 16,
        "loss": 0,
        "name": "Nott'm Forest",
        "played": 0,
        "points": 0,
        "position": 0,
        "short_name": "NFO",
        "strength": 3,
        "team_division": None,
        "unavailable": False,
        "win": 0,
        "strength_overall_home": 1090,
        "strength_overall_away": 1100,
        "strength_attack_home": 1085,
        "strength_attack_away": 1115,
        "strength_defence_home": 1090,
        "strength_defence_away": 1090,
        "pulse_id": 15,
    }


@pytest.fixture
def team_fixture_newcastle():
    return {
            "code": 4,
            "draw": 0,
            "form": None,
            "id": 15,
            "loss": 0,
            "name": "Newcastle",
            "played": 0,
            "points": 0,
            "position": 0,
            "short_name": "NEW",
            "strength": 4,
            "team_division": None,
            "unavailable": False,
            "win": 0,
            "strength_overall_home": 1130,
            "strength_overall_away": 1285,
            "strength_attack_home": 1100,
            "strength_attack_away": 1185,
            "strength_defence_home": 1160,
            "strength_defence_away": 1380,
            "pulse_id": 23,
    }

@pytest.fixture
def team_bootstrap_data(team_fixture_forest, team_fixture_newcastle):
    return {
        "teams": [
            team_fixture_forest,
            team_fixture_newcastle,
        ]
    }
