"""Fixtures for tests."""

import pytest

from fpl_wrapper.model.managers_models import ManagerTeamData


@pytest.fixture
def fixture_player_match_fixture_data():
    """Fixture for player faixture data."""
    return {
        "id": 1,
        "code": 100,
        "team_h": 1,
        "team_h_score": 2,
        "team_a": 2,
        "team_a_score": 1,
        "event": 1,
        "finished": True,
        "minutes": 90,
        "provisional_start_time": False,
        "kickoff_time": "2023-10-01T12:30:00Z",
        "event_name": "Gameweek 1",
        "is_home": True,
        "difficulty": 3,
    }


@pytest.fixture
def fixture_history_data():
    """Fixture for current season data"""
    return {
        "element": 1,
        "fixture": 1,
        "opponent_team": 2,
        "total_points": 10,
        "was_home": True,
        "kickoff_time": "2023-10-01T12:30:00Z",
        "team_h_score": 2,
        "team_a_score": 1,
        "round": 1,
        "minutes": 90,
        "goals_scored": 1,
        "assists": 1,
        "clean_sheets": 1,
        "goals_conceded": 0,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "saves": 0,
        "bonus": 3,
        "bps": 30,
        "influence": "100.0",
        "creativity": "50.0",
        "threat": "75.0",
        "ict_index": "225.0",
        "starts": 1,
        "expected_goals": "0.5",
        "expected_assists": "0.3",
        "expected_goal_involvements": "0.8",
        "expected_goals_conceded": "0.2",
        "value": 100,
        "transfers_balance": 10,
        "selected": 1000,
        "transfers_in": 50,
        "transfers_out": 40,
    }


@pytest.fixture
def fixture_history_past_data():
    """Fixture for past season data data."""
    return {
        "season_name": "2022/23",
        "element_code": 1,
        "start_cost": 100,
        "end_cost": 110,
        "total_points": 200,
        "minutes": 3000,
        "goals_scored": 20,
        "assists": 10,
        "clean_sheets": 15,
        "goals_conceded": 25,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 1,
        "yellow_cards": 3,
        "red_cards": 0,
        "saves": 0,
        "bonus": 30,
        "bps": 300,
        "influence": "500.0",
        "creativity": "200.0",
        "threat": "300.0",
        "ict_index": "1000.0",
        "starts": 35,
        "expected_goals": "10.0",
        "expected_assists": "5.0",
        "expected_goal_involvements": "15.0",
        "expected_goals_conceded": "20.0",
    }


@pytest.fixture
def fixture_player_detail_data():
    """Fixture for player detail data."""
    return {
        "chance_of_playing_next_round": 0,
        "chance_of_playing_this_round": 0,
        "code": 438098,
        "cost_change_event": 0,
        "cost_change_event_fall": 0,
        "cost_change_start": -1,
        "cost_change_start_fall": 1,
        "dreamteam_count": 0,
        "element_type": 3,
        "ep_next": "0.0",
        "ep_this": "0.0",
        "event_points": 0,
        "first_name": "Fábio",
        "form": "0.0",
        "id": 1,
        "in_dreamteam": False,
        "news": "Has joined Portuguese side FC Porto on loan for the 2024/25 season",
        "news_added": "2024-08-29T11:06:25.241953Z",
        "now_cost": 54,
        "photo": "438098.jpg",
        "points_per_game": "0.0",
        "second_name": "Ferreira Vieira",
        "selected_by_percent": "0.0",
        "special": False,
        "squad_number": None,
        "status": "u",
        "team": 1,
        "team_code": 3,
        "total_points": 0,
        "transfers_in": 439,
        "transfers_in_event": 0,
        "transfers_out": 2172,
        "transfers_out_event": 664,
        "value_form": "0.0",
        "value_season": "0.0",
        "web_name": "Fábio Vieira",
        "region": None,
        "minutes": 0,
        "goals_scored": 0,
        "assists": 0,
        "clean_sheets": 0,
        "goals_conceded": 0,
        "own_goals": 0,
        "penalties_saved": 0,
        "penalties_missed": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "saves": 0,
        "bonus": 0,
        "bps": 0,
        "influence": "0.0",
        "creativity": "0.0",
        "threat": "0.0",
        "ict_index": "0.0",
        "starts": 0,
        "expected_goals": "0.00",
        "expected_assists": "0.00",
        "expected_goal_involvements": "0.00",
        "expected_goals_conceded": "0.00",
        "influence_rank": 628,
        "influence_rank_type": 284,
        "creativity_rank": 627,
        "creativity_rank_type": 286,
        "threat_rank": 617,
        "threat_rank_type": 280,
        "ict_index_rank": 631,
        "ict_index_rank_type": 287,
        "corners_and_indirect_freekicks_order": None,
        "corners_and_indirect_freekicks_text": "",
        "direct_freekicks_order": None,
        "direct_freekicks_text": "",
        "penalties_order": None,
        "penalties_text": "",
        "expected_goals_per_90": 0,
        "saves_per_90": 0,
        "expected_assists_per_90": 0,
        "expected_goal_involvements_per_90": 0,
        "expected_goals_conceded_per_90": 0,
        "goals_conceded_per_90": 0,
        "now_cost_rank": 167,
        "now_cost_rank_type": 104,
        "form_rank": 627,
        "form_rank_type": 286,
        "points_per_game_rank": 627,
        "points_per_game_rank_type": 286,
        "selected_rank": 593,
        "selected_rank_type": 260,
        "starts_per_90": 0,
        "clean_sheets_per_90": 0,
    }


@pytest.fixture
def fixture_player_data(
    fixture_player_match_fixture_data,
    fixture_history_data,
    fixture_history_past_data,
):
    return {
        "fixtures": [fixture_player_match_fixture_data],
        "history": [fixture_history_data],
        "history_past": [fixture_history_past_data],
    }


@pytest.fixture
def fixture_players_bootstrap_data(fixture_player_detail_data):
    """Fixture for bootstrap data."""
    return {
        "chips": [],
        "events": [],
        "game_settings": {},
        "game_config": {},
        "phases": [],
        "teams": [],
        "total_players": 0,
        "elements": [fixture_player_detail_data],
        "element_stats": [],
        "element_types": [],
    }


@pytest.fixture
def fixture_league_data():
    """Fixture for league data."""
    return {
        "new_entries": {"has_next": False, "page": 1, "results": []},
        "last_updated_data": "2024-09-28T19:49:21Z",
        "league": {
            "id": 1,
            "name": "Arsenal",
            "created": "2024-07-17T11:51:46.252125Z",
            "closed": False,
            "max_entries": None,
            "league_type": "s",
            "scoring": "c",
            "admin_entry": None,
            "start_event": 1,
            "code_privacy": "p",
            "has_cup": True,
            "cup_league": None,
            "rank": None,
        },
        "standings": {
            "has_next": True,
            "page": 1,
            "results": [
                {
                    "id": 46599801,
                    "event_total": 96,
                    "player_name": "Ajdin Selimovic",
                    "rank": 1,
                    "last_rank": 193,
                    "rank_sort": 1,
                    "total": 513,
                    "entry": 5932784,
                    "entry_name": "Ronaldinhovic",
                },
                {
                    "id": 9178578,
                    "event_total": 53,
                    "player_name": "tunjay ozer",
                    "rank": 2,
                    "last_rank": 1,
                    "rank_sort": 2,
                    "total": 508,
                    "entry": 1432938,
                    "entry_name": "yeah buddy",
                },
                {
                    "id": 49695302,
                    "event_total": 72,
                    "player_name": "Khalil Nasreddin",
                    "rank": 3,
                    "last_rank": 46,
                    "rank_sort": 3,
                    "total": 498,
                    "entry": 6139538,
                    "entry_name": "النصر لحمااس",
                },
                {
                    "id": 14428798,
                    "event_total": 48,
                    "player_name": "Youssef Ben Turkia",
                    "rank": 4,
                    "last_rank": 2,
                    "rank_sort": 4,
                    "total": 495,
                    "entry": 2197936,
                    "entry_name": "Selim1925",
                },
                {
                    "id": 3273903,
                    "event_total": 73,
                    "player_name": "دردقي بشيش",
                    "rank": 5,
                    "last_rank": 97,
                    "rank_sort": 5,
                    "total": 494,
                    "entry": 524830,
                    "entry_name": "فانتازي دبنقا",
                },
                {
                    "id": 51752719,
                    "event_total": 58,
                    "player_name": "Al-Hamza Al-Absi",
                    "rank": 6,
                    "last_rank": 18,
                    "rank_sort": 6,
                    "total": 492,
                    "entry": 6309120,
                    "entry_name": "Maestro",
                },
                {
                    "id": 7385956,
                    "event_total": 72,
                    "player_name": "Elwazzan Elwazzan",
                    "rank": 7,
                    "last_rank": 133,
                    "rank_sort": 7,
                    "total": 491,
                    "entry": 1160256,
                    "entry_name": "الوزان",
                },
                {
                    "id": 45590678,
                    "event_total": 85,
                    "player_name": "Sileman Harki",
                    "rank": 8,
                    "last_rank": 834,
                    "rank_sort": 8,
                    "total": 491,
                    "entry": 5863704,
                    "entry_name": "silemankurdi",
                },
                {
                    "id": 21829325,
                    "event_total": 82,
                    "player_name": "Barham Jabara",
                    "rank": 9,
                    "last_rank": 658,
                    "rank_sort": 9,
                    "total": 490,
                    "entry": 3212728,
                    "entry_name": "barham1234",
                },
                {
                    "id": 63953654,
                    "event_total": 70,
                    "player_name": "James Jeffery",
                    "rank": 10,
                    "last_rank": 150,
                    "rank_sort": 10,
                    "total": 488,
                    "entry": 7586446,
                    "entry_name": "Jeffery10 United",
                },
                {
                    "id": 57264230,
                    "event_total": 60,
                    "player_name": "Ibrahim Alamamy",
                    "rank": 11,
                    "last_rank": 23,
                    "rank_sort": 11,
                    "total": 488,
                    "entry": 6875353,
                    "entry_name": "B E M O",
                },
                {
                    "id": 21084873,
                    "event_total": 89,
                    "player_name": "عمر أبوحكيم",
                    "rank": 12,
                    "last_rank": 2485,
                    "rank_sort": 12,
                    "total": 486,
                    "entry": 3113192,
                    "entry_name": "صہٰاحہٰبٰٰ الُِڪوُرة",
                },
                {
                    "id": 61679379,
                    "event_total": 43,
                    "player_name": "Ahmed Ditto",
                    "rank": 13,
                    "last_rank": 5,
                    "rank_sort": 13,
                    "total": 485,
                    "entry": 7350500,
                    "entry_name": "Ditto.FC",
                },
                {
                    "id": 1207293,
                    "event_total": 59,
                    "player_name": "24 JAM",
                    "rank": 14,
                    "last_rank": 26,
                    "rank_sort": 14,
                    "total": 485,
                    "entry": 197639,
                    "entry_name": "Caterpillar",
                },
                {
                    "id": 68754206,
                    "event_total": 46,
                    "player_name": "ahmed khaled",
                    "rank": 15,
                    "last_rank": 8,
                    "rank_sort": 15,
                    "total": 484,
                    "entry": 8076406,
                    "entry_name": "ابوكتف�",
                },
                {
                    "id": 10549293,
                    "event_total": 77,
                    "player_name": "Jan Popelínský",
                    "rank": 16,
                    "last_rank": 432,
                    "rank_sort": 16,
                    "total": 484,
                    "entry": 1636078,
                    "entry_name": "SexyMan",
                },
                {
                    "id": 4228484,
                    "event_total": 64,
                    "player_name": "Nikola Vasić",
                    "rank": 17,
                    "last_rank": 150,
                    "rank_sort": 17,
                    "total": 482,
                    "entry": 673844,
                    "entry_name": "Argoulides",
                },
                {
                    "id": 1873910,
                    "event_total": 85,
                    "player_name": "Salim Suleiman",
                    "rank": 17,
                    "last_rank": 2393,
                    "rank_sort": 18,
                    "total": 482,
                    "entry": 302997,
                    "entry_name": "Gwena FC",
                },
                {
                    "id": 24211267,
                    "event_total": 82,
                    "player_name": "Tiago T",
                    "rank": 19,
                    "last_rank": 1701,
                    "rank_sort": 19,
                    "total": 482,
                    "entry": 3526742,
                    "entry_name": "Tielemans Square1989",
                },
                {
                    "id": 69505316,
                    "event_total": 57,
                    "player_name": "muhammad naim",
                    "rank": 20,
                    "last_rank": 58,
                    "rank_sort": 20,
                    "total": 482,
                    "entry": 8152480,
                    "entry_name": "Arsenal07",
                },
                {
                    "id": 14771159,
                    "event_total": 55,
                    "player_name": "Yonael Afework",
                    "rank": 21,
                    "last_rank": 45,
                    "rank_sort": 21,
                    "total": 482,
                    "entry": 2246314,
                    "entry_name": "yonaellll",
                },
                {
                    "id": 16507214,
                    "event_total": 64,
                    "player_name": "Erik Pettersson",
                    "rank": 22,
                    "last_rank": 176,
                    "rank_sort": 22,
                    "total": 481,
                    "entry": 2489812,
                    "entry_name": "FC Bendtnerlona",
                },
                {
                    "id": 10793269,
                    "event_total": 47,
                    "player_name": "Kye Calvy",
                    "rank": 23,
                    "last_rank": 22,
                    "rank_sort": 23,
                    "total": 480,
                    "entry": 1670842,
                    "entry_name": "CUCU CUCURELLA",
                },
                {
                    "id": 8888216,
                    "event_total": 61,
                    "player_name": "Hashem ZR",
                    "rank": 24,
                    "last_rank": 139,
                    "rank_sort": 24,
                    "total": 480,
                    "entry": 1388490,
                    "entry_name": "HashemZr",
                },
                {
                    "id": 26830106,
                    "event_total": 49,
                    "player_name": "Hridesh Wagle",
                    "rank": 25,
                    "last_rank": 7,
                    "rank_sort": 25,
                    "total": 480,
                    "entry": 3860569,
                    "entry_name": "GoodBoy Gunner �",
                },
                {
                    "id": 48513986,
                    "event_total": 64,
                    "player_name": "Sayed Ali",
                    "rank": 26,
                    "last_rank": 243,
                    "rank_sort": 26,
                    "total": 479,
                    "entry": 6053249,
                    "entry_name": "قلب البابا",
                },
                {
                    "id": 46933185,
                    "event_total": 50,
                    "player_name": "rebin ali",
                    "rank": 27,
                    "last_rank": 32,
                    "rank_sort": 27,
                    "total": 479,
                    "entry": 5953948,
                    "entry_name": "shery fantasy",
                },
                {
                    "id": 37522503,
                    "event_total": 56,
                    "player_name": "nyamwanga boy",
                    "rank": 27,
                    "last_rank": 75,
                    "rank_sort": 28,
                    "total": 479,
                    "entry": 5135935,
                    "entry_name": "TANZANIA  1",
                },
                {
                    "id": 8574633,
                    "event_total": 74,
                    "player_name": "Benny Angeles",
                    "rank": 27,
                    "last_rank": 932,
                    "rank_sort": 29,
                    "total": 479,
                    "entry": 1340247,
                    "entry_name": "115 Charges FC",
                },
                {
                    "id": 11871468,
                    "event_total": 77,
                    "player_name": "Andy Neale",
                    "rank": 30,
                    "last_rank": 819,
                    "rank_sort": 30,
                    "total": 479,
                    "entry": 1826126,
                    "entry_name": "Arteta's Vision",
                },
                {
                    "id": 10559941,
                    "event_total": 61,
                    "player_name": "Paul Abbott",
                    "rank": 31,
                    "last_rank": 176,
                    "rank_sort": 31,
                    "total": 478,
                    "entry": 1637688,
                    "entry_name": "Roaring Wild Shins",
                },
                {
                    "id": 46755814,
                    "event_total": 68,
                    "player_name": "upi 0opah",
                    "rank": 32,
                    "last_rank": 494,
                    "rank_sort": 32,
                    "total": 478,
                    "entry": 5942818,
                    "entry_name": "elweskheen",
                },
                {
                    "id": 25672458,
                    "event_total": 75,
                    "player_name": "Terry Khawaja",
                    "rank": 32,
                    "last_rank": 1199,
                    "rank_sort": 33,
                    "total": 478,
                    "entry": 3710566,
                    "entry_name": "Bad boys for life",
                },
                {
                    "id": 62880879,
                    "event_total": 54,
                    "player_name": "Stergios Andreoglou",
                    "rank": 34,
                    "last_rank": 65,
                    "rank_sort": 34,
                    "total": 478,
                    "entry": 7475598,
                    "entry_name": "Gunners 21",
                },
                {
                    "id": 45460069,
                    "event_total": 77,
                    "player_name": "Ahmed Ali",
                    "rank": 34,
                    "last_rank": 1507,
                    "rank_sort": 35,
                    "total": 478,
                    "entry": 5855477,
                    "entry_name": "2الزنجي المعجزه",
                },
                {
                    "id": 29454720,
                    "event_total": 70,
                    "player_name": "Ahmed Madkour",
                    "rank": 36,
                    "last_rank": 740,
                    "rank_sort": 36,
                    "total": 477,
                    "entry": 4131524,
                    "entry_name": "HOBI",
                },
                {
                    "id": 32714067,
                    "event_total": 88,
                    "player_name": "Adam Brismo",
                    "rank": 36,
                    "last_rank": 5639,
                    "rank_sort": 37,
                    "total": 477,
                    "entry": 4548098,
                    "entry_name": "HeMan",
                },
                {
                    "id": 53769495,
                    "event_total": 61,
                    "player_name": "Paul Ovens",
                    "rank": 38,
                    "last_rank": 224,
                    "rank_sort": 38,
                    "total": 477,
                    "entry": 6502948,
                    "entry_name": "haven’tgotimeforthis",
                },
                {
                    "id": 1975973,
                    "event_total": 73,
                    "player_name": "Karan Vir Negi",
                    "rank": 38,
                    "last_rank": 1066,
                    "rank_sort": 39,
                    "total": 477,
                    "entry": 319175,
                    "entry_name": "Old Havertz Kai Hard",
                },
                {
                    "id": 56125796,
                    "event_total": 82,
                    "player_name": "Augustine Ebubeogu",
                    "rank": 38,
                    "last_rank": 3016,
                    "rank_sort": 40,
                    "total": 477,
                    "entry": 6753586,
                    "entry_name": "Stinelee",
                },
                {
                    "id": 17870856,
                    "event_total": 85,
                    "player_name": "David Jones",
                    "rank": 38,
                    "last_rank": 4145,
                    "rank_sort": 41,
                    "total": 477,
                    "entry": 2679834,
                    "entry_name": "Djibouti FC",
                },
                {
                    "id": 53553071,
                    "event_total": 60,
                    "player_name": "Sam Callcut",
                    "rank": 42,
                    "last_rank": 193,
                    "rank_sort": 42,
                    "total": 477,
                    "entry": 6479949,
                    "entry_name": "Saka White Rice",
                },
                {
                    "id": 27814024,
                    "event_total": 66,
                    "player_name": "Abdulio .",
                    "rank": 42,
                    "last_rank": 432,
                    "rank_sort": 43,
                    "total": 477,
                    "entry": 3945686,
                    "entry_name": "King Kai",
                },
                {
                    "id": 14154386,
                    "event_total": 57,
                    "player_name": "James Morris",
                    "rank": 44,
                    "last_rank": 133,
                    "rank_sort": 44,
                    "total": 476,
                    "entry": 2156730,
                    "entry_name": "Jim's Janglies",
                },
                {
                    "id": 4658691,
                    "event_total": 66,
                    "player_name": "Yehia 🇪🇬🇵🇸",
                    "rank": 44,
                    "last_rank": 480,
                    "rank_sort": 45,
                    "total": 476,
                    "entry": 741337,
                    "entry_name": "Yehia",
                },
                {
                    "id": 30139986,
                    "event_total": 57,
                    "player_name": "Louie Heron",
                    "rank": 46,
                    "last_rank": 133,
                    "rank_sort": 46,
                    "total": 476,
                    "entry": 4216381,
                    "entry_name": "Mosgiel Metapods",
                },
                {
                    "id": 51066576,
                    "event_total": 92,
                    "player_name": "yassin zakaria",
                    "rank": 46,
                    "last_rank": 9876,
                    "rank_sort": 47,
                    "total": 476,
                    "entry": 6261743,
                    "entry_name": "yassinzakaria",
                },
                {
                    "id": 61203460,
                    "event_total": 83,
                    "player_name": "Yahia Ltf",
                    "rank": 48,
                    "last_rank": 4145,
                    "rank_sort": 48,
                    "total": 475,
                    "entry": 7299374,
                    "entry_name": "Quelle BUT",
                },
                {
                    "id": 3139680,
                    "event_total": 54,
                    "player_name": "Mohamed Ali",
                    "rank": 49,
                    "last_rank": 100,
                    "rank_sort": 49,
                    "total": 475,
                    "entry": 503352,
                    "entry_name": "Three (A)",
                },
                {
                    "id": 12261491,
                    "event_total": 56,
                    "player_name": "Alex Scofield",
                    "rank": 49,
                    "last_rank": 130,
                    "rank_sort": 50,
                    "total": 475,
                    "entry": 1883694,
                    "entry_name": "Scözil XI",
                },
            ],
        },
    }


@pytest.fixture
def picks_data_no_chip():
    return {
        "active_chip": None,
        "automatic_subs": [],
        "entry_history": {
            "event": 1,
            "points": 54,
            "total_points": 54,
            "rank": 5141847,
            "rank_sort": 5141847,
            "overall_rank": 5141845,
            "percentile_rank": 60,
            "bank": 5,
            "value": 1000,
            "event_transfers": 0,
            "event_transfers_cost": 0,
            "points_on_bench": 5,
        },
        "picks": [
            {
                "element": 201,
                "position": 1,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 422,
                "position": 2,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 3,
                "position": 3,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 333,
                "position": 4,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 366,
                "position": 5,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 317,
                "position": 6,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 54,
                "position": 7,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 17,
                "position": 8,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": True,
            },
            {
                "element": 351,
                "position": 9,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 401,
                "position": 10,
                "multiplier": 2,
                "is_captain": True,
                "is_vice_captain": False,
            },
            {
                "element": 82,
                "position": 11,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 536,
                "position": 12,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 19,
                "position": 13,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 255,
                "position": 14,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 275,
                "position": 15,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
        ],
    }


@pytest.fixture
def fixture_picks_data_wildcard():
    return {
        "active_chip": "wildcard",
        "automatic_subs": [],
        "entry_history": {
            "event": 1,
            "points": 54,
            "total_points": 54,
            "rank": 5141847,
            "rank_sort": 5141847,
            "overall_rank": 5141845,
            "percentile_rank": 60,
            "bank": 5,
            "value": 1000,
            "event_transfers": 0,
            "event_transfers_cost": 0,
            "points_on_bench": 5,
        },
        "picks": [
            {
                "element": 201,
                "position": 1,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 422,
                "position": 2,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 3,
                "position": 3,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 333,
                "position": 4,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 366,
                "position": 5,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 317,
                "position": 6,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 54,
                "position": 7,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 17,
                "position": 8,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": True,
            },
            {
                "element": 351,
                "position": 9,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 401,
                "position": 10,
                "multiplier": 2,
                "is_captain": True,
                "is_vice_captain": False,
            },
            {
                "element": 82,
                "position": 11,
                "multiplier": 1,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 536,
                "position": 12,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 19,
                "position": 13,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 255,
                "position": 14,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
            {
                "element": 275,
                "position": 15,
                "multiplier": 0,
                "is_captain": False,
                "is_vice_captain": False,
            },
        ],
    }


@pytest.fixture
def fixture_team_forest():
    return {
        "code": 17,
        "draw": 0,
        "form": None,
        "id": 16,
        "loss": 0,
        "name": "Nott'm Forest",
        "played": 0,
        "points": 0,
        "position": 0,
        "short_name": "NFO",
        "strength": 3,
        "team_division": None,
        "unavailable": False,
        "win": 0,
        "strength_overall_home": 1090,
        "strength_overall_away": 1100,
        "strength_attack_home": 1085,
        "strength_attack_away": 1115,
        "strength_defence_home": 1090,
        "strength_defence_away": 1090,
        "pulse_id": 15,
    }


@pytest.fixture
def fixture_team_newcastle():
    return {
        "code": 4,
        "draw": 0,
        "form": None,
        "id": 15,
        "loss": 0,
        "name": "Newcastle",
        "played": 0,
        "points": 0,
        "position": 0,
        "short_name": "NEW",
        "strength": 4,
        "team_division": None,
        "unavailable": False,
        "win": 0,
        "strength_overall_home": 1130,
        "strength_overall_away": 1285,
        "strength_attack_home": 1100,
        "strength_attack_away": 1185,
        "strength_defence_home": 1160,
        "strength_defence_away": 1380,
        "pulse_id": 23,
    }


@pytest.fixture
def fixture_team_bootstrap_data(fixture_team_forest, fixture_team_newcastle):
    return {
        "teams": [
            fixture_team_forest,
            fixture_team_newcastle,
        ]
    }


@pytest.fixture
def fixture_player_picks_list(fixture_picks_data_wildcard, picks_data_no_chip):
    """Fixture for test_get_player_analysis."""
    return [
        ManagerTeamData(**picks_data_no_chip),
        ManagerTeamData(**fixture_picks_data_wildcard),
    ]


@pytest.fixture()
def fixture_player_event():
    return {
        "code": 2444470,
        "event": 1,
        "finished": True,
        "finished_provisional": True,
        "id": 1,
        "kickoff_time": "2024-08-16T19:00:00Z",
        "minutes": 90,
        "provisional_start_time": False,
        "started": True,
        "team_a": 9,
        "team_a_score": 0,
        "team_h": 14,
        "team_h_score": 1,
        "is_home": True,
        "difficulty": 1,
        "stats": [
            {
                "identifier": "goals_scored",
                "a": [],
                "h": [{"value": 1, "element": 389}],
            },
            {
                "identifier": "assists",
                "a": [],
                "h": [{"value": 1, "element": 372}],
            },
            {"identifier": "own_goals", "a": [], "h": []},
            {"identifier": "penalties_saved", "a": [], "h": []},
            {"identifier": "penalties_missed", "a": [], "h": []},
            {
                "identifier": "yellow_cards",
                "a": [
                    {"value": 1, "element": 240},
                    {"value": 1, "element": 241},
                    {"value": 1, "element": 243},
                ],
                "h": [
                    {"value": 1, "element": 377},
                    {"value": 1, "element": 382},
                ],
            },
            {"identifier": "red_cards", "a": [], "h": []},
            {
                "identifier": "saves",
                "a": [{"value": 4, "element": 248}],
                "h": [{"value": 2, "element": 383}],
            },
            {
                "identifier": "bonus",
                "a": [],
                "h": [
                    {"value": 3, "element": 389},
                    {"value": 2, "element": 594},
                    {"value": 1, "element": 369},
                    {"value": 1, "element": 380},
                ],
            },
            {
                "identifier": "bps",
                "a": [
                    {"value": 16, "element": 249},
                    {"value": 15, "element": 240},
                    {"value": 15, "element": 255},
                    {"value": 13, "element": 245},
                    {"value": 12, "element": 248},
                    {"value": 11, "element": 19},
                    {"value": 10, "element": 251},
                    {"value": 7, "element": 257},
                    {"value": 5, "element": 239},
                    {"value": 5, "element": 241},
                    {"value": 5, "element": 247},
                    {"value": 4, "element": 254},
                    {"value": 4, "element": 259},
                    {"value": 3, "element": 252},
                    {"value": 2, "element": 243},
                    {"value": 2, "element": 256},
                ],
                "h": [
                    {"value": 33, "element": 389},
                    {"value": 32, "element": 594},
                    {"value": 26, "element": 369},
                    {"value": 26, "element": 380},
                    {"value": 25, "element": 383},
                    {"value": 22, "element": 377},
                    {"value": 21, "element": 378},
                    {"value": 19, "element": 368},
                    {"value": 11, "element": 364},
                    {"value": 11, "element": 372},
                    {"value": 10, "element": 366},
                    {"value": 5, "element": 385},
                    {"value": 3, "element": 381},
                    {"value": 3, "element": 593},
                    {"value": 2, "element": 371},
                    {"value": -1, "element": 382},
                ],
            },
            {"identifier": "mng_underdog_win", "a": [], "h": []},
            {"identifier": "mng_underdog_draw", "a": [], "h": []},
        ],
        "team_h_difficulty": 3,
        "team_a_difficulty": 3,
        "pulse_id": 115827,
    }


@pytest.fixture()
def fixture_get_event(fixture_player_event):
    return [fixture_player_event]


@pytest.fixture()
def fixture_chip():
    return {
        "id": 1,
        "name": "wildcard",
        "number": 1,
        "start_event": 2,
        "stop_event": 19,
        "chip_type": "transfer",
        "overrides": {
            "rules": {},
            "scoring": {},
            "element_types": [],
            "pick_multiplier": None,
        },
    }


@pytest.fixture()
def fixture_game_settings():
    return {
        "game_settings": {
            "league_join_private_max": 30,
            "league_join_public_max": 5,
            "league_max_size_public_classic": 20,
            "league_max_size_public_h2h": 16,
            "league_max_size_private_h2h": 16,
            "league_max_ko_rounds_private_h2h": 3,
            "league_prefix_public": "League",
            "league_points_h2h_win": 3,
            "league_points_h2h_lose": 0,
            "league_points_h2h_draw": 1,
            "league_ko_first_instead_of_random": None,
            "cup_start_event_id": None,
            "cup_stop_event_id": None,
            "cup_qualifying_method": None,
            "cup_type": None,
            "featured_entries": [],
            "element_sell_at_purchase_price": False,
            "percentile_ranks": [
                1,
                5,
                10,
                15,
                20,
                25,
                30,
                35,
                40,
                45,
                50,
                55,
                60,
                65,
                70,
                75,
                80,
                95,
                90,
                95,
            ],
            "underdog_differential": 5,
            "squad_squadplay": 11,
            "squad_squadsize": 15,
            "squad_special_min": None,
            "squad_special_max": None,
            "squad_team_limit": 3,
            "squad_total_spend": 1000,
            "ui_currency_multiplier": 10,
            "ui_use_special_shirts": False,
            "ui_special_shirt_exclusions": [],
            "stats_form_days": 30,
            "sys_vice_captain_enabled": True,
            "transfers_cap": 20,
            "transfers_sell_on_fee": 0.5,
            "max_extra_free_transfers": 4,
            "league_h2h_tiebreak_stats": ["+goals_scored", "-goals_conceded"],
            "timezone": "UTC",
        }
    }


@pytest.fixture()
def fixture_config_settings():
    return {
        "settings": {"entry_per_event": False, "timezone": "UTC"},
        "rules": {
            "league_join_private_max": 30,
            "league_join_public_max": 5,
            "league_max_size_public_classic": 20,
            "league_max_size_public_h2h": 16,
            "league_max_size_private_h2h": 16,
            "league_max_ko_rounds_private_h2h": 3,
            "league_prefix_public": "League",
            "league_points_h2h_win": 3,
            "league_points_h2h_lose": 0,
            "league_points_h2h_draw": 1,
            "league_ko_first_instead_of_random": False,
            "cup_start_event_id": None,
            "cup_stop_event_id": None,
            "cup_qualifying_method": None,
            "cup_type": None,
            "featured_entries": [],
            "element_sell_at_purchase_price": False,
            "percentile_ranks": [
                1,
                5,
                10,
                15,
                20,
                25,
                30,
                35,
                40,
                45,
                50,
                55,
                60,
                65,
                70,
                75,
                80,
                95,
                90,
                95,
            ],
            "underdog_differential": 5,
            "squad_squadplay": 11,
            "squad_squadsize": 15,
            "squad_special_min": None,
            "squad_special_max": None,
            "squad_team_limit": 3,
            "squad_total_spend": 1000,
            "ui_currency_multiplier": 10,
            "ui_use_special_shirts": False,
            "ui_special_shirt_exclusions": [],
            "stats_form_days": 30,
            "sys_vice_captain_enabled": True,
            "transfers_cap": 20,
            "transfers_sell_on_fee": 0.5,
            "max_extra_free_transfers": 4,
            "league_h2h_tiebreak_stats": ["+goals_scored", "-goals_conceded"],
        },
        "scoring": {
            "long_play": 2,
            "short_play": 1,
            "goals_conceded": {
                "DEF": -1,
                "FWD": 0,
                "GKP": -1,
                "MID": 0,
                "MNG": 0,
            },
            "saves": 1,
            "goals_scored": {"DEF": 6, "FWD": 4, "GKP": 10, "MID": 5, "MNG": 0},
            "assists": 3,
            "clean_sheets": {"DEF": 4, "FWD": 0, "GKP": 4, "MID": 1, "MNG": 0},
            "penalties_saved": 5,
            "penalties_missed": -2,
            "yellow_cards": -1,
            "red_cards": -3,
            "own_goals": -2,
            "bonus": 1,
            "bps": 0,
            "influence": 0,
            "creativity": 0,
            "threat": 0,
            "ict_index": 0,
            "special_multiplier": 1,
            "mng_goals_scored": {
                "DEF": 0,
                "FWD": 0,
                "GKP": 0,
                "MID": 0,
                "MNG": 1,
            },
            "mng_clean_sheets": {
                "DEF": 0,
                "FWD": 0,
                "GKP": 0,
                "MID": 0,
                "MNG": 2,
            },
            "mng_win": {"DEF": 0, "FWD": 0, "GKP": 0, "MID": 0, "MNG": 6},
            "mng_draw": {"DEF": 0, "FWD": 0, "GKP": 0, "MID": 0, "MNG": 3},
            "mng_loss": 0,
            "mng_underdog_win": {
                "DEF": 0,
                "FWD": 0,
                "GKP": 0,
                "MID": 0,
                "MNG": 10,
            },
            "mng_underdog_draw": {
                "DEF": 0,
                "FWD": 0,
                "GKP": 0,
                "MID": 0,
                "MNG": 5,
            },
        },
    }


@pytest.fixture()
def fixture_event_bootstrap():
    return {
        "id": 1,
        "name": "Gameweek 1",
        "deadline_time": "2024-08-16T17:30:00Z",
        "release_time": None,
        "average_entry_score": 57,
        "finished": True,
        "data_checked": True,
        "highest_scoring_entry": 3546234,
        "deadline_time_epoch": 1723829400,
        "deadline_time_game_offset": 0,
        "highest_score": 127,
        "is_previous": False,
        "is_current": False,
        "is_next": False,
        "cup_leagues_created": False,
        "h2h_ko_matches_created": False,
        "can_enter": False,
        "can_manage": False,
        "released": True,
        "ranked_count": 8597356,
        "overrides": {
            "rules": {},
            "scoring": {},
            "element_types": [],
            "pick_multiplier": None,
        },
        "chip_plays": [
            {"chip_name": "bboost", "num_played": 144974},
            {"chip_name": "3xc", "num_played": 221430},
        ],
        "most_selected": 401,
        "most_transferred_in": 27,
        "top_element": 328,
        "top_element_info": {"id": 328, "points": 14},
        "transfers_made": 0,
        "most_captained": 351,
        "most_vice_captained": 351,
    }


@pytest.fixture()
def fixture_element_type():
    return (
        {
            "id": 1,
            "plural_name": "Goalkeepers",
            "plural_name_short": "GKP",
            "singular_name": "Goalkeeper",
            "singular_name_short": "GKP",
            "squad_select": 2,
            "squad_min_select": None,
            "squad_max_select": None,
            "squad_min_play": 1,
            "squad_max_play": 1,
            "ui_shirt_specific": True,
            "sub_positions_locked": [12],
            "element_count": 77,
        },
    )


@pytest.fixture()
def fixture_bootstrap_data(
    fixture_chip,
    fixture_event_bootstrap,
    fixture_config_settings,
    fixture_game_settings,
    fixture_team_forest,
    fixture_player_detail_data,
    fixture_element_type,
):
    return {
        "chips": [fixture_chip],
        "events": [fixture_event_bootstrap],
        "game_settings": fixture_game_settings,
        "game_config": fixture_config_settings,
        "phases": [],
        "teams": [fixture_team_forest],
        "total_players": 3,
        "elements": [fixture_player_detail_data],
        "element_stats": [{}],
        "element_types": fixture_element_type,
    }


@pytest.fixture()
def fixture_manager_basic():
    return {
        "id": 2407187,
        "joined_time": "2024-07-26T21:32:01.847297Z",
        "started_event": 1,
        "favourite_team": 1,
        "player_first_name": "Brian",
        "player_last_name": "Galligan",
        "player_region_id": 104,
        "player_region_name": "Ireland",
        "player_region_iso_code_short": "IE",
        "player_region_iso_code_long": "IRL",
        "years_active": 14,
        "summary_overall_points": 1409,
        "summary_overall_rank": 2648181,
        "summary_event_points": 88,
        "summary_event_rank": 2012701,
        "current_event": 24,
        "leagues": {
            "classic": [
                {
                    "id": 1,
                    "name": "Arsenal",
                    "short_name": "team-1",
                    "created": "2024-07-17T11:51:46.252125Z",
                    "closed": False,
                    "rank": None,
                    "max_entries": None,
                    "league_type": "s",
                    "scoring": "c",
                    "admin_entry": None,
                    "start_event": 1,
                    "entry_can_leave": False,
                    "entry_can_admin": False,
                    "entry_can_invite": False,
                    "has_cup": True,
                    "cup_league": 2451205,
                    "cup_qualified": True,
                    "rank_count": 1769184,
                    "entry_percentile_rank": 25,
                    "active_phases": [
                        {
                            "phase": 1,
                            "rank": 404610,
                            "last_rank": 424962,
                            "rank_sort": 404663,
                            "total": 1409,
                            "league_id": 1,
                            "rank_count": 1769184,
                            "entry_percentile_rank": 25,
                        },
                        {
                            "phase": 8,
                            "rank": 297842,
                            "last_rank": 0,
                            "rank_sort": 298095,
                            "total": 88,
                            "league_id": 1,
                            "rank_count": 1769183,
                            "entry_percentile_rank": 20,
                        },
                    ],
                    "entry_rank": 404610,
                    "entry_last_rank": 424962,
                },
            ],
            "h2h": [
                {
                    "id": 521600,
                    "name": "IN IT TO WIN IT",
                    "short_name": None,
                    "created": "2024-07-29T20:49:23.364914Z",
                    "closed": True,
                    "rank": None,
                    "max_entries": None,
                    "league_type": "x",
                    "scoring": "h",
                    "admin_entry": 2018250,
                    "start_event": 1,
                    "entry_can_leave": False,
                    "entry_can_admin": False,
                    "entry_can_invite": False,
                    "has_cup": False,
                    "cup_league": None,
                    "cup_qualified": None,
                    "rank_count": None,
                    "entry_percentile_rank": None,
                    "active_phases": [],
                    "entry_rank": 16,
                    "entry_last_rank": 16,
                }
            ],
            "cup": {
                "matches": [],
                "status": {
                    "qualification_event": None,
                    "qualification_numbers": None,
                    "qualification_rank": None,
                    "qualification_state": None,
                },
                "cup_league": None,
            },
            "cup_matches": [
                {
                    "id": 58565833,
                    "entry_1_entry": 9747778,
                    "entry_1_name": "GHUR",
                    "entry_1_player_name": "Freddy Ferguson",
                    "entry_1_points": 55,
                    "entry_1_win": 0,
                    "entry_1_draw": 0,
                    "entry_1_loss": 0,
                    "entry_1_total": 0,
                    "entry_2_entry": 2407187,
                    "entry_2_name": "Ricecakes",
                    "entry_2_player_name": "Brian Galligan",
                    "entry_2_points": 42,
                    "entry_2_win": 0,
                    "entry_2_draw": 0,
                    "entry_2_loss": 0,
                    "entry_2_total": 0,
                    "is_knockout": True,
                    "league": 2421396,
                    "winner": 9747778,
                    "seed_value": None,
                    "event": 15,
                    "tiebreak": None,
                    "is_bye": False,
                    "knockout_name": "Round of 16777216",
                },
            ],
        },
        "name": "Ricecakes",
        "name_change_blocked": False,
        "entered_events": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
        ],
        "kit": '{"kit_shirt_type":"plain","kit_shirt_base":"#c92a2a","kit_shirt_sleeves":"#ffffff","kit_shirt_secondary":"#E1E1E1","kit_shirt_logo":"pl-primary-stars","kit_shorts":"#ffffff","kit_socks_type":"plain","kit_socks_base":"#4a90e2","kit_socks_secondary":"#E1E1E1"}',
        "last_deadline_bank": 29,
        "last_deadline_value": 1028,
        "last_deadline_total_transfers": 28,
    }
